backend/coreapp/compiler_wrapper.py
backend/coreapp/tests.py

I added a test for this as well, which I'll continue to do for new fixes and features. You run the tests from the backend dir by simply doing `python3 manage.py test`. (Fixes #98)

Support .late_rodata in scratch creation

---

backend/coreapp/asm_diff_wrapper.py
backend/coreapp/tests.py

Added a test that creates a scratch and calls compile via the API. This will catch future integration issues with asm-differ.

Add /scratch/<slug>/compile test

---

backend/asm_differ/.gitrepo
backend/asm_differ/diff.py
backend/coreapp/asm_diff_wrapper.py
frontend/src/diff/Diff.module.css

Pretty small change. Imported fixes from `asm_differ`, then disabled `show_line_numbers` & `show_source` in the config.
Result screenshot:

Fix duplicated line numbers by using new version of `asm_differ`

---

frontend/src/lib/api.ts

I don't fully understand the issue here - as Ethan was saying in the Discord, `localScratch` always seems `undefined` inside `updateLocalScratch` -- even *after* it has been set, even several renders later. (e.g. it's not `undefined` outside of that fn).

Possibly fix refresh bug? (suspense issue?)

---

backend/Dockerfile
backend/compilers/download.sh
backend/compilers/gcc2.7kmc/config.json
frontend/src/components/compiler/PresetSelect.tsx
frontend/src/components/compiler/compilers/gcc2.7kmc.tsx
frontend/src/components/compiler/compilers/index.ts

It requires the cpp from `gcc-mips-linux-gnu` so make sure you install that as part of the deployment :+1:

Adding KMC GCC 2.7

---

backend/coreapp/sandbox.py

This should fix the issues with `wine` we were having on Ubuntu. 
There is a wine [patch ](https://www.mail-archive.com/debian-wine@lists.debian.org/msg00433.html) which tries to put the `wineserver` temp files in a directory we have mapped as read-only in the `nsjail`. Adding `/run/user/$UID` as a writeable directory changes the logic to put the temp files there instead.

Add `/run/user/$UID` directory to nsjail

---

.github/workflows/pr.yml
backend/Dockerfile
backend/requirements.txt
docker-compose.yaml

A few changes:
1. Install `python3` into an Ubuntu 21.04 base image, use this instead of the python3.9-bullseye which is based on Debian 11
2. Create and use a non-root user, `user`, to catch any weird root-related permissions issues
3. ~~Use `/home/user/.wine` as the WINEPREFIX as that is more in-line with Production~~
4. Use `psycopg2-binary` instead of compiling `psycopg2` from source (seemed to be required for latest Ubuntu)

Update backend Dockerfile to Ubuntu 21.04 to align with Prod

---

backend/compilers/mwcc.sh
backend/compilers/mwcc_247_108_pikmin2/config.json
frontend/src/components/compiler/PresetSelect.tsx
frontend/src/components/compiler/compilers/index.ts
frontend/src/components/compiler/compilers/mwcc_247_108_pikmin2.tsx

also remove unnecessary compiler logic/config for an obsolete compiler fork

update Pikmin and Pikmin 2 presets

---

backend/compilers/mwcc.sh
backend/compilers/mwcc_233_163e/config.json
frontend/src/components/compiler/PresetSelect.tsx

Until 1.2.5 can be patched to match expected behaviour, this is the best solution at the time of writing...

Update 1.2.5e to use frank.py

---

frontend/src/components/Diff/Diff.module.css
frontend/src/components/Diff/Diff.tsx

This PR makes the diff spread across 100% of the available space, with each column taking up 50% of the space.
It also makes the diff header - 'TARGET' and 'CURRENT' - stay visible as you scroll (requested by @Wrymouth).

Use flexbox for Diff layout instead of tables

---

frontend/src/components/Diff/Diff.module.css
frontend/src/components/Diff/Diff.tsx
frontend/src/pages/theme.scss

Builds on #252:
- Fixes layout on mobile; thin viewports will not cause the columns to compress (notice horizontal scrollbar in image)
- Reverts to having the columns being left-justified, instead of 50-50
- Various style changes e.g. adds lines between the columns

Improve diff layout

---

backend/coreapp/serializers.py
backend/coreapp/tests.py
backend/coreapp/views/scratch.py

I think this is an ideal way of tackling #175) as we already know a fork is a fork via the ui. adding "fork of" is just going to get spammy I think
closes #175

Copy scratch name to fork

---

frontend/src/components/Scratch/ScratchBody.tsx
frontend/src/lib/api.ts
frontend/src/pages/scratch/[slug].tsx

- use single-tab mode at 800px instead of 200px
- render scratch pages dynamically
- reduce args to api.forkScratch

Fix issues introduced in previous PR

---

backend/coreapp/compiler_wrapper.py
backend/coreapp/github.py
backend/coreapp/models.py
backend/coreapp/views/user.py
frontend/src/components/Diff/Diff.module.css
frontend/src/components/GitHubLoginButton.tsx
frontend/src/components/Nav/LoginState.tsx
frontend/src/components/Nav/Nav.module.scss
frontend/src/components/Scratch/AboutScratch.module.scss
frontend/src/components/Scratch/AboutScratch.tsx
frontend/src/components/Scratch/ScratchToolbar.module.scss
frontend/src/components/user/UserLink.tsx
frontend/src/lib/api.ts
frontend/src/pages/login.module.css
frontend/src/pages/login.tsx
frontend/src/pages/scratch/[slug].tsx

- A few style tweaks, like removing the border-bottom from the navbar and the scratch toolbar.
- On login, scratches created anonymously are now assigned to the user.
- The login popup looks and behaves a bit better now.
- The size of the Target pane of diffs is now limited to 40 characters in width to avoid [this insanity with triple-figure symbol names](https://media.discordapp.net/attachments/897066363951128590/926142330891800657/unknown.png).

Login UX improvements

---

frontend/src/components/compiler/PresetSelect.tsx

the flag obfuscates errors; we've removed it

Remove msgstyle gcc

---

backend/compilers/agbcc/config.json
backend/coreapp/compiler_wrapper.py

Expands the yaml parser to allow for a list format wherein multiple compilers can be specified for the same base directory
Adds old_agbcc as a compiler
Reduces verbosity of some of the logs for loading compilers

Clean compiler loading logs and allow multiple compilers per dir

---

backend/coreapp/compiler_wrapper.py

The majority of arm9 code was compiled in thumb mode (at least for the Pokémon projects). This change adds a flag to assemble asm in thumb mode, as well. This fixes the issue where instruction widths were not matching for NDS scratches.
See example scratch with fix applied:

Assemble NDS asm in thumb mode

---

frontend/src/components/compiler/PresetSelect.tsx

-str pool isn't needed, except on maybe specific files, -Cpp_exceptions off removes a tag in Current asm so functions can match Target asm

Update TTYD Preset

---

backend/compilers/ido5.3/config.json
backend/compilers/ido7.1/config.json
backend/coreapp/compiler_wrapper.py
backend/coreapp/tests.py
frontend/src/components/compiler/PresetSelect.tsx
frontend/src/components/compiler/compiler_settings/ido.tsx

Makes -non_shared no longer an implicit ido flag. Adds it to all existing presets and creates a UI selector for -non_shared or -KPIC. Adds Dinosaur Planet preset for its DLLs

Support -KPIC for IDO

---

backend/coreapp/asm_diff_wrapper.py
backend/coreapp/compiler_wrapper.py

...and only when a diff_label was specified by the user.
For some modern platforms it's impossible to force the compiler to only generate code for a single function *even if* the source code and context tabs only contain one function: the compiler may need to generate e.g. PLT stubs for position-independent code.

Use objdump --disassemble to avoid diffing past function end (when possible)

---

backend/coreapp/asm_diff_wrapper.py

For obvious reasons, function and variable addresses will not match the
original code. asm-differ has an option to ignore address differences
and make the diff less noisy. (This only has an effect for 32-bit ARM
and AArch64 at the moment.)

backend: Ignore address differences when diffing code

---

backend/coreapp/asm_diff_wrapper.py

Fixes problems with diffing target asm (section labels not showing up, among possibly other things)

Give target asm object to asm_differ as a byte array

---

backend/compilers/clang-3.9.1/config.json
backend/compilers/clang.sh

By adding the compiler flag `-D_LIBCPP_HAS_MUSL_LIBC`, the broken parts of musl/clang can be circumvented. The [testing scratch](https://decomp.me/scratch/MaJuR) compiles fine with this on version 3.9.1.

backend: Fix `musl` for `clang-3.9.1`

---

.env
README.md
backend/coreapp/models.py
backend/coreapp/serializers.py
backend/decompme/settings.py
docker-compose.yaml

As this configuration setting seems to be unused at the moment, it can be removed. This removes all references to the environment variable and local python storage in the backend, as well as the README and one comment still referring to that name.

Remove `FRONTEND_BASE`

---

frontend/src/components/Scratch/ScratchToolbar.tsx
frontend/src/lib/api.ts

Related: Issue [#326](https://github.com/decompme/decomp.me/issues/326)
This fixes the exporting of scratches as `zip` files from the site.
Due to earlier changes, it seems like some endpoint for scratches was moved between frontend and backend. The `scratch.url` only contains the "ending" of the URL, so for example `/scratch/bvwj6`. It does *not* contain the URL/API http-endpoint, so the browser relates it to the frontend instead of the backend. Instead, the URL has to be resolved to point to the exporting part of the backend.
As the duplicate code would start to pile up for resolving this kind of "URL-ending" to a full URL, I moved that to a separate function that can be called for directly getting API data, or only for resolving the URL like in this case.

frontend: Fix scratch exporting (#326)

---

.github/workflows/pr.yml
.gitignore
backend/Dockerfile
backend/docker_entrypoint.sh
docker-compose.yaml

This PR changes the poetry behaviour to match the approach we take for the `frontend`, where the dependencies are pulled down at runtime, and cached locally (in this case `/backend/virtualenvs` vs than `/frontend/node_modules`) so that future instantiations are speedy:
e.g. frontend:
```
frontend_1  | yarn install v1.22.17
frontend_1  | [1/4] Resolving packages...
frontend_1  | success Already up-to-date.
```
and backend:
```
backend_1   | Installing dependencies from lock file
backend_1   | No dependencies to install or update
```
I also pinned poetry to the current version, `1.1.13`.

execute 'poetry install' at runtime, same as yarn install

---

backend/coreapp/error.py
backend/coreapp/models/github.py
frontend/src/components/GitHubLoginButton.tsx
frontend/src/lib/api.ts
frontend/src/lib/oauth.ts
frontend/src/pages/login.tsx

Fixes #390, although without the deployment stuff mentioned + `scopes` is not stored in the database (because we can just lazily raise MissingOAuthScopeException if the GitHub API complains that we lack permission for an action).
- request oauth scopes only when server asks
- don't require public_repo

Request OAuth scopes on-demand

---

backend/coreapp/platforms.py
backend/coreapp/tests.py

Adds fpr register aliases for MIPS (specifically for the O32 ABI).
This should not affect negatively any code which does not use those aliases.
I didn't add them for PS1 because from what I understand the PS1 does not have a floating point processing unit

Add prelude.inc with support for abi fpr names for Nintendo64 MIPS

---

backend/mips_to_c/.gitrepo
backend/mips_to_c/src/parse_file.py

subrepo:
subdir:   "backend/mips_to_c"
merged:   "762dc9e4"
upstream:
origin:   "https://github.com/matt-kempster/mips_to_c"
branch:   "master"
commit:   "762dc9e4"
git-subrepo:
origin:   "https://github.com/ingydotnet/git-subrepo"

M2C update

---

.github/workflows/pr.yml
backend/Dockerfile

They just closed https://github.com/google/nsjail/issues/190 so updating the Dockerfile to use it!

Use nsjail release 3.1 now its been cut

---

backend/coreapp/compiler_wrapper.py
backend/coreapp/serializers.py
backend/coreapp/tests.py
backend/coreapp/views/scratch.py
frontend/src/pages/new.tsx

-woff was being filtered out of compiler flags upon scratch creation
diff_flags was being passed incorrectly to the backend

Fix settings bugs

---

backend/coreapp/compilers.py

Another preset will likely be added for PAL and another for Trilogy, hence the naming.

Add Metroid Prime (USA) preset

---

backend/compilers/download.py
backend/coreapp/compiler_wrapper.py
backend/coreapp/compilers.py
backend/coreapp/platforms.py
backend/coreapp/views/scratch.py
frontend/locales/en/compilers.json
frontend/src/components/PlatformSelect/PlatformIcon.tsx
frontend/src/components/PlatformSelect/macos9.svg
frontend/src/pages/credits.tsx

Adds:
-The cross-compiler (target is Mac OS 9 (PowerPC), and host is Win32) and linker from Metrowerks CodeWarrior Pro 5 and 6.
-Some changes to work around the compilers' jank and work around the proprietary format used for the object files by dumping the assembly, converting it to a format binutils can assemble, and assembling a linux elf that can be dumped with objdump
-A preset for the aforementioned cross-compiler: The Sims 1, with flags "-lang=c++ -O3 -str pool -g"
As there is no version of doldisasm.py but for PEF files instead of DOLs (due to PEFs not only being proprietary, but also poorly documented and having no existing python library to use; I'm too lazy to implement an entire PEF reader in python myself as PEFs are really complex), scratches need to have the input asm be asm …

Add MWCPPC (Mac OS 9 cross compiler ran on windows)

---

frontend/src/components/PlatformSelect/PlatformSelect.module.scss

Updates PlatformSelect to use a grid of three columns. This should prevent [whatever happened in #462](https://github.com/decompme/decomp.me/pull/462#issuecomment-1145940121), and also prevents the cells from growing to more than one column when there are less than three on a row (see: last cell width in image below).

use grid instead of flex in PlatformSelect

---

backend/compilers/download.py

Accounts for .align directives now

Fix convert_gas_syntax script in MACOSX compilers

---

frontend/src/components/Diff/Diff.module.scss
frontend/src/components/Diff/Diff.tsx

Poor man's register highlighting: run a regex client side to tokenize lines and make it possible to click tokens to highlight them on that side of the diff. (You can highlight different tokens on both sides, in order to trace register diffs.) Double-clicking highlights a token on both sides. Only one token can be highlighted at a time, and clicking a non-token clears all highlighting.
(The double-click behavior is kinda undiscoverable and unideal... I could imagine selecting the corresponding token on the other side automatically when the lines match up completely, or showing a help message about the double click functionality when the user highlights the same thing on both sides manually, or moving the highlight-only-on-one-side functionality to under a modifier key.)

Highlight tokens in the diff view on click

---

docs/SHORTCUTS.md

Added a short doc on keyboard shortcuts and formatting to the docs directory - still currently has the <span style="color:...."> tags, though not sure if they'll show correctly on Github or not.

add shortcuts and formatting guide to docs

---

backend/coreapp/compiler_wrapper.py

In MWCC versions 3.0+, using `#line` directives to override line numbers in the dwarf output won't work unless the file given in the directive exists (the contents of it don't matter). This PR changes the second directive from `src.c` to `code.c` since that file already exists, and creates an empty `ctx.c` file to fix the first directive.

MWCC line number fix

---

.github/workflows/ci.yml
backend/Dockerfile
backend/coreapp/compiler_wrapper.py
backend/coreapp/compilers.py

1. $TMPDIR is only used by PSYQ with certain optimisation levels / codegen, hence why it's mostly been working
2. Updated wibo to latest version, this fixes a few missing functions
3. Added `-quiet` flag to the PSYQ assembler
Fixes #491

Add TMPDIR=/tmp to compiler command

---

backend/coreapp/compilers.py

Updates Pikmin 1 and 2 compiler presets based on updated knowledge from the project ('-common on' flag should be used due to bss locations). Likely to cause zero change to majority of scratches using the presets (as far as we know or have seen, since it's bss-related), but would be good to keep it consistent with native build just in case.

Update Pikmin 1+2 presets

---

backend/coreapp/compiler_wrapper.py
backend/coreapp/compilers.py
backend/coreapp/sandbox.py

NDS MWCC outputs correct line numbers to stdout in the following format
```
Z:\var\folders\mv\5b1057tx3pgbq60mm6p07y0h0000gn\T\tmpreq_0h7l\ctx.c:7: note:     (corresponding #line reference)
```
Usually this gets interleaved with stderr in the command line, 
```
Z:\var\folders\mv\5b1057tx3pgbq60mm6p07y0h0000gn\T\tmpreq_0h7l\code.c:13: warning: illegal implicit conversion from 'int' to
Z:\var\folders\mv\5b1057tx3pgbq60mm6p07y0h0000gn\T\tmpreq_0h7l\code.c:13: warning: 'struct asdf_struct *'
Z:\var\folders\mv\5b1057tx3pgbq60mm6p07y0h0000gn\T\tmpreq_0h7l\ctx.c:7: note:     (corresponding #line reference)
```
...but split stdout/stderr makes it unusable since all the notes get tacked onto the end.
This PR tries to take each `corresponding #line reference` and match it up with (usually multiple) …

Fix incorrect line numbers on NDS MWCC

---

.github/workflows/ci.yml
backend/compilers/download.py
backend/coreapp/diff_wrapper.py
backend/coreapp/tests.py
backend/poetry.lock
backend/pyproject.toml

Taking my test from #503 into a separate PR, because I think this should be merged in ASAP

Do a sanity test for every available compiler

---

backend/coreapp/models/profile.py
backend/coreapp/serializers.py
frontend/src/components/Nav/Search.tsx
frontend/src/components/user/AnonymousFrog.module.scss
frontend/src/components/user/AnonymousFrog.tsx
frontend/src/components/user/UserAvatar.tsx
frontend/src/lib/api.ts

As per #389 and #513.
This PR assigns all users a random color (generated by seeding a RNG from the ID of their profile), used as the base color of a frog for anonymous users in place of a profile picture.
Currently, it's used everywhere a proper profile picture is used, with the exception of the LoginState component - it felt a little cleaner keeping it as exclusively text. (As ever, open to changing that :))

Colorful frog avatars for anonymous users

---

frontend/src/components/Scratch/ScratchToolbar.module.scss

Maybe
Chrome 83 Android before:

Fix scratch action icons having overflowing text on old Chrome

---

frontend/src/components/Nav/Nav.tsx

On all pages except the scratch editor, middle-clicking the top-left corner (the frog icon) opens the
home page in a new tab. On the editor, doing the same action -- although with the hamburger menu icon
rather than the frog -- does nothing. This PR makes middle-clicking the hamburger menu icon open the
home page in a new tab, so muscle memory enjoyers like @Brotenko can use it on the editor too.

Open index page when middle-clicking on hamburger menu

---

backend/compilers/download.py

I think github strips the +x flag from the binary - kinda irritating.

Update psyq-obj-parser for psyq compilers

---

backend/coreapp/compilers.py

This means I no longer need to worry about assembler flags...
e.g. (passing the `-v` flag in to show what programs were called + their args:
```
CCPSX 3.02 Build 0002 (Win32 version 3.01, PSX version 3.02)
cpppsx -undef -D__GNUC__=2 -v -D__OPTIMIZE__ -lang-c -Dmips -D__mips__ -D__mips -Dpsx -D__psx__ -D__psx -D_PSYQ -D__EXTENSIONS__ -D_MIPSEL -D__CHAR_UNSIGNED__ -D_LANGUAGE_C -DLANGUAGE_C /tmp/code.c /tmp/PQ2 
cc1psx -quiet -version -O2 -G0 /tmp/PQ2 -o /tmp/PQ3 
aspsx -q -G0 /tmp/PQ3 -o /tmp/object.o.obj 
```
.. and then setting `-G4`:
```
CCPSX 3.02 Build 0002 (Win32 version 3.01, PSX version 3.02)
cpppsx -undef -D__GNUC__=2 -v -D__OPTIMIZE__ -lang-c -Dmips -D__mips__ -D__mips -Dpsx -D__psx__ -D__psx -D_PSYQ -D__EXTENSIONS__ -D_MIPSEL -D__CHAR_UNSIGNED__ -D_LANGUAGE_C -DLANGUAGE_C …
```

Switch PSYQ to use CCPSX instead of CC1PSX+ASPSX chain

---

backend/compilers/download.py
backend/coreapp/compilers.py
frontend/next.config.js

This should probably fix the issues that were going on with getting it to work.
What I had to do was update the assembler syntax converter, as its detection of branches wasn't working right (the regex was expecting 2 tabs when there was only one).

(hopefully) fix macos9 compiler

---

backend/asm_differ/diff.py
backend/coreapp/platforms.py

PS2's  Emotion Engine has some custom instructions like `mult rd,rs,rt` and `madd` which weren't recognized as instructions with `-march=mips64`, so this PR just switches to `-march=r5900` which correctly handles the new instructions

Set the correct march for PS2 assembler

---

backend/coreapp/diff_wrapper.py
backend/coreapp/flags.py
backend/coreapp/platforms.py
frontend/locales/en/compilers.json

Adds a new checkbox for disabling pseudo instructions on MIPS scratches by passing the `-Mno-aliases` flag to `objdump`. This is disabled by default.
Because GAS likes using the same pseudo instruction for multiple instructions, which sometimes leads to confusion of "why this doesn't match if it is the same instruction". Complains about this usually happen with the `li` pseudo instruction.
Example ("both are `li`s, why it doesn't match?!?!?"):
Disabling pseudos ("oh, they actually are different instructions"):
Some pseudos are clearer as pseudos than their actual raw instruction; like for example the `nop`, which gets disassembled as `sll, zero, zero, 0x0`. `move` is also an example of this (even if the underlying instruction changes depending on the assembler).
There doesn't seem to be …

Checkbox for disabling pseudo instructions for MIPS

---

backend/coreapp/compilers.py

This PR adds a preset for Luigi's Mansion. However, I am babby, so the compiler options included are the bare minimum used while matching isolated functions. They will probably need to be updated once the full pool of options is found.

Add preliminary compiler options for Luigi's Mansion

---

backend/coreapp/compilers.py

Adds compiler presets for the 4 ELF files in the Ratatouille GameCube prototype: https://hiddenpalace.org/Disney-Pixar_Ratatouille_(Jan_18,_2006_prototype)

Add Ratatouille Prototype presets

---

frontend/src/components/GhostButton.tsx
frontend/src/components/ScoreBadge.tsx
frontend/src/components/Scratch/AboutScratch.tsx
frontend/src/components/Scratch/FamilyPanel.tsx
frontend/src/components/Scratch/Scratch.tsx
frontend/src/components/Scratch/SortableFamilyList.tsx
frontend/src/components/user/UserLink.tsx

See it in action: click the Family tab of https://decomp.me/scratch/2LQOY on the deployment (press 'View deployment'):
Todo:

Add family page back in tab form

---

backend/coreapp/compilers.py

- We figured out a few better presets for egcs which we believe will be enabled for almost every project that uses this specific compiler
- This also adds a preset for the iQue version of Dr. Mario 64 and libultra

Change egcs defaults and add two presets

---

backend/coreapp/compilers.py

The correct compiler version for KAIN2.EXE is "mostly" PsyQ 4.3.
The AADLIB is what uses 4.5 I think so it's probably best to use 4.3 since 80% of the code is using that.

Update LoK: SR compiler version and flags

---

frontend/src/app/(navfooter)/new/page.tsx
frontend/src/components/PlatformSelect/PlatformName.tsx
frontend/src/lib/api.ts
frontend/src/lib/api/request.ts

This should fix #597. It's hard to say, since I can't reproduce it.
I *think* the problem lay in the API not providing an age for `/compilers` using the `Cache-Control` or `Expires` headers. Combined with frontend's `api.getCached`, which does a fetch but - crucially - with `cache: "default"` instead of `cache: "no-cache"` ([docs](https://developer.mozilla.org/en-US/docs/Web/API/Request/cache#value)). In "default", because there's no age given on the resource, [the browser will use implementation-defined heuristics](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#heuristic_caching) to decide whether to use the cached version - which is what I think is happening here.
Problem is, we don't know in advance when the compilers will change. This could have gone two ways:
1. Send a …

remove api.getCached

---

backend/compilers/download.py
backend/coreapp/compilers.py

Updates recomp ido to v0.5 which has slight differences in how it handles file path redirection.
Please let me know if there is something else I need to update as well.

Update IDO recomp to v0.5

---

backend/coreapp/platforms.py

https://decomp.me/scratch/LdpMr has a bunch of annoying diffs of the form:
```diff
- 78:    beqz    at,L802CA24C_6DB8FC+0x78
+ 78:    beqz    at,2ec ~>
```
which appear because there's a glabel L802CA24C_6DB8FC in between branch and target that the branch decides to relocate against. If the label is made local this won't happen. `L802CA24C_6DB8FC:` may not work for all decomps, because of jtbl targets needing to be referenceable by separately compiled rodata, but `jlabel L802CA24C_6DB8FC` would, if made to expand to `L802CA24C_6DB8FC:` on decomp.me and `glabel L802CA24C_6DB8FC` locally.
decomp-permuter, m2c and splat already support `jlabel` since before; it was originally devised by @Mr-Wiseguy "mainly for the purpose of progress calculation".

Add jlabel macro for MIPS platforms

---

frontend/src/app/scratch/[slug]/page.tsx

Fixes #685.
The issue was that scratch pages were statically rendered and cached indefinitely upon first request. The client was requesting the most up-to-date scratch data from Django but didn't realise that it was out-of-date compared to what the Next.js server gave it. The simplest fix for this is to never cache scratch pages, rerendering them on every request with the latest data.

dynamically render scratch pages

---

backend/coreapp/views/scratch.py

allow families to include scratches with differing compilers

Make families larger

---

backend/coreapp/sandbox.py

Untested. See https://docs.python.org/3/library/io.html#io.TextIOWrapper for the allowed values of `errors`.

Accept malformed UTF-8 in compiler output

---

backend/compilers/download.py
backend/coreapp/compilers.py

This changes the directory layout of the compiler so that the batch files and absolute paths aren't needed. This also includes the change by @Ced2911 to use objcopy to convert the coff to elf. I don't understand why this is necessary for some inputs on certain systems but it seems to work fine locally.

Fix saturn path issue and use objcopy to convert to elf

---

frontend/src/components/Scratch/SortableFamilyList.tsx

Also reverse sort of Last Modified to have most recent first, I think this makes more sense overall since people generally want the more recent ones, so they should go in the consistent screen position, at the top.

Tiebreak family sorting by score using Last Modified

---

backend/compilers/download.py

I tested this by running the download.py script multiple times outside the container. I think this should fix situations where saturn-compilers-main is out of date, or cygnus-2.7-96Q3 already exists.

Remove saturn directories when downloading

---

backend/coreapp/compilers.py

Enable debug symbols so we get line highlighting for the current assembly

Add debug symbols for PMD:Red

---

frontend/src/components/ScoreBadge.module.scss

make score 'tick' white rather than theme-dependent

---

frontend/src/components/Diff/Diff.tsx

Reported by @Kelebek1. (Haven't tested this change yet, edit was made from GitHub editor. Vercel might make that convenient.)

Don't highlight brackets on click

---

backend/compilers/download.py
backend/coreapp/compilers.py
backend/coreapp/migrations/0032_replace_ps2_991111_with_991111a.py
frontend/src/lib/i18n/locales/en/compilers.json

This compiler is required to get this scratch this to match: https://decomp.me/scratch/oPCWT
I also added a few notes at the top of that scratch detailing the differences between 991111, 991111-01, and the 991111 Windows build that the site currently uses (I'll call this 991111-win). 991111 can be compiled from source so Wine wouldn't have to be used, though it produces different code than 991111-win, so I'm not sure how to proceed with adding that compiler version.
(technically 991111 should be `ee-gcc2.9-991111` and 991111-win should be moved to a separate compiler ID like `ee-gcc2.9-991111-win` to avoid confusion since 991111-win seems to be a compiler version in between 991111 and 991111-01, though that means certain scratches that need 991111-win would have to change the compiler …

Add ee-gcc2.9-991111-01 compiler

---

frontend/next.config.js

The [documentation](https://nodejs.org/api/child_process.html#child_processexeccommand-options-callback) says that "pipe" is the default option, but it's [clearly not](https://stackoverflow.com/a/45578119/7290888). This change consumes any stderr from the `git rev-parse HEAD` command rather than spitting it out in the log.
**Before:**
```
decompme-frontend-1  | fatal: not a git repository (or any parent up to mount point /)
decompme-frontend-1  | Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
decompme-frontend-1  | Unable to get git hash, assume running inside Docker
```
**After:**
```
decompme-frontend-1  | Unable to get git hash, assume running inside Docker
```

Consume stderr when checking git hash

---

backend/compilers/download.py

Melee is usually the main motivator for frank updates, as the vast majority of melee code needs 1.2.5e, so most frank updates hit melee first. I'm also currently held up on syncing pikmin's frank.py with melee's, as the latest update to frank needs python 3.8 and pikmin's CI is on 3.7. https://github.com/projectPiki/pikmin/pull/9

Use doldecomp/melee as source for frank.py

---

backend/compilers/download.py
backend/coreapp/compilers.py
frontend/src/lib/i18n/locales/en/compilers.json

Due to a quirk with the GameCube Animal Crossing line (DnM+, AC, DnMe+), .rodata is not pooled while .data and .bss are. There is likely a set of flags which reproduces this behavior, but we could not determine them.
Instead, we have modified mwcceppc 1.3.2 to force disable data pooling for the .rodata section with the 1.3.2r compiler variant.

Add mwcceppc 1.3.2r & update AC preset

---

backend/coreapp/tests.py
backend/coreapp/views/scratch.py

thanks to @mkst for helping debug 
Closes #811

Make family more liberal

---

backend/coreapp/compilers.py

Fix vib-ribbon preset

---

backend/coreapp/compiler_wrapper.py
backend/coreapp/compilers.py

#488 fixed the DWARF line numbers for newer GC/Wii compilers (which just required the files containing code to exist), but made error messages messy in the process.
The error messages show both the version of the line from the preprocessed file, and the version from the original based on the info given from `#line`.
- The preprocessed code is stored in `code.c`, which also has a `#line` statement half way through claiming to be the start of `code.c`. This meant that the line of code shown in the second half of the error message that looks up the `#line` would just be a random unrelated line from the file.
- Any context errors would just show a blank line in the second half of the error messaage
- The first half of the message would show the correct line contents, but the line number would …

Fix gc/wii error messages

---

backend/coreapp/compilers.py

This PR updates the vib-ribbon preset to switch from the PSYQ 4.5 compiler to vanilla GCC 2.91.66.

Update vib-ribbon preset

---

backend/coreapp/platforms.py

The latest capstone update now uses these names isntead of just raw numbers to refer to the condition register, so any projects using assembly generated by that will need these to be able to assemble

Add ppc cr definitions

---

backend/compilers/download.py

Fixes #820
Adds `-fprologue-bugfix` and whatever else is new in agbcc since January 2022

Switch agbcc to follow pret's fork

---

backend/coreapp/compilers.py

Fixes #836 by adding a flag to specify the location of intermediate files (in /tmp/)

Fix MSVC compilers

---

backend/coreapp/compilers.py

LEGO Island is C++ code.
I took what was in the original CMakeLists file (https://github.com/isledecomp/isle/blob/master/CMakeLists.txt) but I guess CMake automatically puts in this flag. Other flags like the /Gz or something allowing for __stdcalls might be necessary in the future, but for now this is important.

LEGO Island preset - pass /TP (C++) compiler flag

---

backend/compilers/download.py

I accidentally broke that when MRing my MSVC7.0 toolchain. Woops.

Fix downloading OmniBlade MSVC toolchains

---

backend/compilers/download.py
backend/coreapp/compilers.py
frontend/src/lib/i18n/locales/en/compilers.json

One more compiler to the collection =)
Co-authored-by: @mkst

add GCC 2.8.0-mipsel for PSX

---

backend/compilers/download.py
backend/coreapp/compilers.py

Currently untested, but looks like it should work.

Use 'base_compiler' functionality to dedupe macosx compilers

---

backend/coreapp/serializers.py
backend/coreapp/views/scratch.py

`filter`ing is broken at the moment (see https://stackoverflow.com/a/73887435/7290888).
This doesnt currently work:
```
curl "https://decomp.me/api/scratch?compiler=ido5.3" | jq
```
This PR adds the ability to filter scratches based on the preset (also adds preset to the terse serializer)
```
curl "http://localhost:8000/api/scratch?preset=AeroGauge"
curl "https://decomp.me/api/scratch?preset=AeroGauge" | jq
```
Closes #859.

API - Allow filtering scratches based on preset

---

backend/coreapp/compiler_wrapper.py

With this change:
**server logs:**
```
decompme-backend-1   | 21:23:40 WARNING /backend/compilers/n64/ido5.3 does not exist, creating it!
```
**user message:**
```
/bin/bash: line 1: /backend/compilers/n64/ido5.3/cc: No such file or directory
```
And `download.py` will run successfully because there isn't a file called `/backend/compilers/n64/ido5.3`.
Closes #862.

Ensure compiler.path exists before mounting it

---

backend/coreapp/compilers.py

Add a new "Metal Gear Solid (overlays)" preset that uses `-G0` flag instead of `-G8` flag, as was the case in the "Metal Gear Solid" preset  (preset for the main executable). 
Additionally add `-Wall` flag, because we use it very often in our scratches.

Add "Metal Gear Solid (overlays)" preset

---

backend/libraries/download.py
backend/libraries/libraries.yaml

This PR:
- avoids the warning about git init without naming the branch when downloading libs:
```
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint:     git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint:     git branch -m <name>
```
- Removes an unused `--libraries` argument
- Adds an error if the downloaded repository does not contain an `include` directory
Along with some misc cleanup of the script.

Refactor libraries/download.py

---

.github/workflows/ci.yml
backend/Dockerfile
backend/coreapp/platforms.py

Per the discord conversation. It doesn't look much work to remove devkitpro - we are only using as, objdump and nm, and those utilities are all available to install in ubuntu. For the `arm` platform we already install those binaries (but overwrite them with devkitpro ones - at least in docker, unsure what the production box is using).
I created a GC/Wii scratch (and a Nintendo DS one) locally to test based on a couple of scratches from the live site. Not sure how else to sanity test this change?

Devkitpro be gone

---

backend/coreapp/compilers.py

More investigation was done, and it was discovered that there was an official release of PsyQ GCC 2.6.3. However, it has not surfaced online. I have compiled a Win32 version which is compatible with the original PsyQ toolchain, but this is likely unnecessary for decomp.me

Update Frogger's compiler preset.

---

.github/workflows/ci.yml
backend/Dockerfile
backend/compilers/compilers.linux.yaml
backend/coreapp/compilers.py
frontend/src/lib/i18n/locales/en/compilers.json

Using ngccc.exe is too much trouble (especially given there are no known active projects using the ProDG compilers). We can try to use ngccc.exe another time if the current approach becomes an issue for anyone.
Closes #895.

Add ProDG compilers (GameCube)

---

backend/coreapp/serializers.py
backend/coreapp/tests/test_scratch.py
backend/coreapp/views/scratch.py

Fixes #904. The issue was that the `platform` value was coming back as a `str` in some code paths and a `Platform` in others. Now it should come back as a `Platform`.
Broken test run: https://github.com/decompme/decomp.me/actions/runs/6697436478/job/18197319501

Fix permuter import

---

backend/Dockerfile
backend/compilers/compilers.linux.yaml
backend/coreapp/compilers.py
frontend/src/lib/i18n/locales/en/compilers.json

Also updating the Dockerfile so we always install dosemu.
Note gcc 2.5.7 doesnt support the `-pipe` argument (`-pipe` uses pipes between processes rather than using temporary files) hence it's been removed.

Add gcc 2.5.7 for ps1

---

backend/coreapp/compilers.py

Until https://github.com/decompals/wibo/issues/64 is fixed, let's switch back to wine so these compilers can be used.

Use wine for ProDG compilers

---

backend/coreapp/urls.py
backend/coreapp/views/compiler.py
backend/coreapp/views/library.py
backend/coreapp/views/platform.py
frontend/src/app/(navfooter)/new/page.tsx
frontend/src/components/PlatformSelect/PlatformName.tsx
frontend/src/lib/api.ts

The `/api/compilers` endpoint will still work (i.e. for decomp-permuter looking up decomp.me compilers when import.py is run with --decomp.me).

Singularise 'libraries' and 'compilers' api endpoints

---

frontend/src/components/compiler/PresetSelect.tsx
frontend/src/lib/api.ts

The PATCH to scratch with `preset: undefined` does not set `preset` to `null` - therefore whilst the compiler value will be updated, the preset will still have the original value.
This PR explicitly sets `preset: null` in the PATCH request (along with any other fields that have a local value of `undefined`).
Fixes #939.

Allow saving of custom preset

---

backend/poetry.lock

This PR incorporates [this](https://github.com/matt-kempster/m2c/issues/268) fix which allows %gp_rel to be parsed correctly :+1:

Bump m2c to latest

---

backend/coreapp/compilers.py
frontend/src/lib/i18n/locales/en/compilers.json

Picked this one cos I believe it's the one that Soul Reaver uses (and so we can demonstrate the `-Wa,0` flag.

Add PS1 compiler using CCPSX.EXE (PSYQ4.4)

---

backend/coreapp/diff_wrapper.py

Why does `run_subprocess` + `shell=True` not already do this when you pass it a list? No clue...

Fix diff command escaping

---

backend/coreapp/tests/test_decompilation.py
backend/poetry.lock

Target commit is https://github.com/matt-kempster/m2c/commit/581031e603caa5abf75d26ebfb30bc11a9190a22.
Addresses `.L` style labels being used as callbacks. See https://github.com/matt-kempster/m2c/commit/0514701ef53ce46e91e4e675455c44647714d014 and matt-kempster/m2c#269.

Bump m2c to `581031e`

---

backend/coreapp/diff_wrapper.py

Removes the restrictions on displaying reloc information for Windows platforms as that appears to work correctly after some local testing. Had issues with a DOS scratch so not including that platform for now.

Remove restrictions on i686 reloc use.

---

backend/coreapp/views/scratch.py

Recently, the site experienced massive slowdown, at around 11 AM UTC on February 5th, 2024. I believe that my usage of the API is what caused this.
I was using the `/api/scratch` endpoint to go very far back, filtering by SSBM scratches (`preset=63`). The last request I sent before the site stopped responding was:
```
https://decomp.me/api/scratch?cursor=cD0yMDIyLTA1LTA5KzA2JTNBMjclM0EyOC42NDYxMzYlMkIwMCUzQTAw&format=json&page_size=100&preset=63
```
This PR changes the ordering of the scratch view, as I believe that having a non-fixed ordering is forcing the site to re-index upon requesting records which have been updated since the last indexing. According to the [documentation](https://www.django-rest-framework.org/api-guide/pagination/#cursorpagination):
> Proper usage of cursor …

Change scratch view pagination ordering to `creation_time`

---

backend/coreapp/compiler_wrapper.py
backend/coreapp/views/scratch.py

Does this seem reasonable? It makes exports slightly slower, but I imagine the feature isn't used much (?). I've needed this a couple of times for debugging.

Add current.o to export zip

---

frontend/src/components/compiler/CompilerOpts.tsx

Prevent presets on scratches from being set to null when options change

---

frontend/src/components/compiler/CompilerOpts.tsx
frontend/src/components/compiler/PresetSelect.tsx

Is there a nicer way to write this? We want to set the preset.id to null to clear it in the database, but do not want to change any other scratch configuration.

Allow users to select 'Custom' preset again

---

.github/workflows/ci.yml
backend/Dockerfile
backend/coreapp/diff_wrapper.py
backend/coreapp/platforms.py
backend/poetry.lock

Note that this also gets around an issue involving diffing msvc compiler output for debug/no-inline code. See the changes to diff_wrapper.py.

x86: Update asm-differ and fix some incorrect objdump output by using mingw instead of msdosdjgpp.

---

backend/coreapp/compilers.py
backend/coreapp/flags.py

This is a best effort based on running one of each compiler with the `--help` argument. We can tweak it as necessary.
Closes #1105.

Make MWCCCompiler more granular for each platform

---

.github/workflows/ci.yml
backend/Dockerfile
backend/coreapp/platforms.py

Source: https://github.com/encounter/gc-wii-binutils
Right now there's only one patch to fix mftb instructions, but it's an issue that pops up pretty frequently.

Use custom powerpc-eabi binutils for GC/Wii

---

backend/coreapp/diff_wrapper.py

This works - I feel it's the right place, but open to suggestions.
Edit: If I have a scratch open on `main` and hit refresh, the backend does 12 calls to objdump (6 to run_objdump). With this branch I get 0 as the result is in the lru_cache.

Wrap diff_wrapper.run_objdump in lru_cache

---

frontend/src/components/ScratchList.tsx

Should fix #1112. Opening PR for testing,
This is somewhat of a temporary fix - we should try and consolidate all of the various ScratchList code to simplify things.
**Homepage**
**User**

Fixup owner alignment in ScratchList

---

frontend/src/app/scratch/[slug]/opengraph-image.tsx

[This](https://decomp.me/scratch/ukgQr) scratch currently generates a 500 error. The scratch has no owner:
Broken:
Fixed in this PR:

Fix scratch og when scratch has no owner

---

frontend/src/app/(navfooter)/platform/[id]/page.tsx
frontend/src/app/(navfooter)/preset/[id]/page.tsx
frontend/src/app/(navfooter)/u/[username]/page.tsx

I think it could be nice to say that "User x owners n scratches", but that would require the backend to return num_scratches for users, and that looked like a bit tricky, so it's one for another day.
Before/after for preset:
Before/after for platform:
**TODO:**
Now with thousands separator:

Fix opengraph embed for platform, preset and user

---

frontend/src/app/(navfooter)/WelcomeInfo.tsx
frontend/src/components/Breadcrumbs.tsx
frontend/src/components/Scratch/ScratchToolbar.module.scss

The platform icon being a link was throwing an error in the console - we want the platform icon to link to eg. /platforms/ps1, but the scratch name should be editable - the whole '<icon> scratchName' shouldnt (ever) be a link.
I've stopped the child entry being a link if `href` isn't provided. I'm unsure if there is a nicer way to do this - we only have a maximum of 2 levels of breadcrumbs, so maybe it's ok for now and we can address in the future? Do we want all items except the last one to be anchors? 
I've also also fixed the vertical alignment of the icon:
Before
After:

Fix nested anchor in Scratch Toolbar breadcrumb

---

backend/coreapp/diff_wrapper.py
backend/poetry.lock

We don't need all the functionality of asm-differ's `run_diff()` so pulled out the good bits into decomp.me.

Remove json roundtrip when calling asm-differ

---

frontend/package.json
frontend/src/app/(navfooter)/settings/editor/EditorSettings.tsx
frontend/src/components/Scratch/Scratch.tsx
frontend/src/lib/settings.ts
frontend/yarn.lock

Resolves #1130 by adding vim bindings as an option inside of `/settings/editor`, apologies in advance if I didn't make the most optimal react code, I have worked with it very little. Doesn't seem to cause any lag for me, but I believe that it might be rerendering too much

Add setting for vim bindings to be used

---

frontend/src/components/Scratch/AboutScratch.module.scss

Just adds `text-wrap: nowrap` to `.scratchLinkContainer` to prevent the username and icon container from wrapping and instead just overflowing off the page like everything else :)

One line CSS change to fix #1127

---

frontend/src/components/Scratch/Scratch.tsx

Somewhere along the line we stopped passing `contextCompareExtension` to the context pane.

Fixup vim refs (also fix context comparison)

---

frontend/src/components/Scratch/Scratch.tsx

It is a pattern best avoided, since it causes a re-render after rendering one frame. In this case, refs work just as well.
In addition, this fixes a potential crash from accessing diff_output.current_score, where diff_output may be null. (Reported in Discord chat.)

Avoid changing state in useEffect for progress bar

---

frontend/src/components/Diff/CompilationPanel.tsx

Previously the "Problems" bar could only be toggled by clicking the small icon on the very far right. It would be a more pleasant of a user experience to be able to simply click the bar anywhere to toggle it, as it is much quicker and requires less precision.
This stretches the button to fit the full bar while keeping the spacing of the text an arrow icon as before.

Toggle problems by clicking anywhere on the bar

---

frontend/src/components/ScratchList.tsx
frontend/src/components/compiler/PresetSelect.tsx
frontend/src/lib/api.ts

The *upside* to this change is that rather than getting all compilers + platforms + presets etc via the `/compiler`, we grab each preset as required.
```sh
$ curl --silent https://decomp.me/api/compiler?format=json | wc -c
173635
```
The *downside* to this change is that rather than getting all compilers + platforms + presets etc via the `/compiler`, we grab each preset as required. 
```sh
$ curl --silent "https://decomp.me/api/preset/21?format=json" | wc -c
244
```
I still think this is much better in terms of amount of data being sent & processed - but it is more requests to the backend (I know there is a maximum of 6 outstanding requests per tab, does this also apply to `fetch`)?
~~Gonna see how the vercel deployment looks...~~
**Edit:**
Performance seems good to me... When loading the …

Swap usePlatforms for usePresets/usePreset

---

frontend/src/app/(navfooter)/new/NewScratchForm.tsx
frontend/src/components/Scratch/Scratch.tsx
frontend/src/components/compiler/PresetSelect.tsx
frontend/src/lib/api.ts

- (per ConorB) don't wrap the Options tab in a function to fix the "Problems" issue
- Differentiate between no presets (i.e. either Options tab, or API hasn't returned yet) and empty presets (i.e. PSP platform)
- show "Loading..." whilst waiting for API to return
- Allow user to select "Custom" preset
- Sort presets alphabetically by name
Closes #1157.

make presets great again

---

backend/coreapp/decompiler_wrapper.py
backend/coreapp/tests/test_decompilation.py

e.g.
```
/*
Decompilation failure:
Syntax error when parsing C context.
before: context at line 1, column 5
bad context
*/
/* Decompilation with context failed; here's the decompilation without context: */
void myfunc(void) {
}
```
Closes #1166.

Include M2CError response when decompilation fails due to bad context

---

frontend/src/app/error.tsx

Fixes #870.
I've left `UnexpectedErrorPage` as using `reset` - it feels like a pure client-side rerender might be more appropriate as a recovery option there? I'm open to arguments the other way, too.

Have NetworkErrorPage use `window.location.reload` instead of `reset`

---

backend/coreapp/compilers.py

It seemed like the `TMPDIR` environment variable was being ignored, so I've stuck it in the SN.INI file instead, also echo out more stuff to ensure we are in the directory I expect us to be in!

Add more verbosity to debug CCPSX compiler failure

---

.github/workflows/ci.yml

Closes #1194 as we cannot add non-package configuration until we are on poetry 1.8.0 or more (critter is on 1.3.2, docker is on 1.6.1). 
**Note:** CI currently uses `1.8.2`.

Add '--no-root' to poetry install ci commands

---

backend/coreapp/compilers.py

These were used before presets were migrated to the db.

Small cleanup of unused flags in compilers.py

---

backend/coreapp/compiler_wrapper.py
backend/coreapp/libraries.py
backend/coreapp/views/library.py
backend/coreapp/views/scratch.py
backend/libraries/download.py
backend/libraries/libraries.yaml
frontend/src/components/compiler/CompilerOpts.tsx
frontend/src/lib/api.ts
frontend/src/lib/api/types.ts

We know the platform when we come to use the library, so passing it in here is less intrusive than trying to give all Libraries a platform.
I've also updated the useLibraries / `api/library` view to support `platform=xyz` being passed, the alternative could be to return all libraries and then doing some filtering on the client side. This could be changed if we find ourselves with libraries supporting multiple platforms... or it could be changed now :)

Make libraries platform-specific redux

---

backend/coreapp/serializers.py

Closes #1201.
I'm pretty sure we don't need `language` as part of a terse scratch - it's the only thing making the site explode when a compiler isn't available.

Remove 'language' from TerseScratch serializer

---

frontend/src/app/(navfooter)/settings/account/UserState.tsx

Previous:
Device with screen width 380px or greater:
Device with screen width less than 380px:

Added flexwrap to account anonymous user buttons

---

frontend/src/app/(navfooter)/page.tsx
frontend/src/app/layout.tsx
frontend/src/app/opengraph-image.tsx

key change here is to only draw 5 platform icons (rather than 9) as only 5 fit.

Tweak opengraph rendinger speed

---

frontend/src/app/(navfooter)/u/[username]/page.tsx

Hi @mkst @marijnvdwerf 
Fixed #686 
I have added classes "justify-center md:justify-start" to the div holding github icon and the user name in span tag
This fixed the issue

Fix: misaligned GitHub link on profile page issue 686

---

frontend/src/components/Diff/DragBar.module.scss
frontend/src/components/Diff/DragBar.tsx

After looking at #1217 I thought it would be good to use the same blue highlighting when dragging the bar to resize target/current asm:

Use same blue for diff vertical splitter as horizontal splits

---

backend/coreapp/serializers.py
backend/coreapp/tests/test_preset.py
frontend/src/lib/api/types.ts

In scratch api, we get the full profile with username and user's id in owner field. However in preset we were only getting the id.
<table>
<tr>
<td> Before </td> <td> After </td>
</tr>
<tr>
<td> 
```json
{
"id": 2,
"name": "random",
"platform": "dummy",
"compiler": "dummy",
"assembler_flags": "-dummy-asm",
"compiler_flags": "-dummy-compiler",
"diff_flags": {},
"decompiler_flags": "-decompiler",
"libraries": [],
"num_scratches": 0,
"owner": 2
}
```
</td>
<td> 
```json
{
"id": 2,
"name": "random",
"platform": "dummy",
"compiler": "dummy",
"assembler_flags": "-dummy-asm",
"compiler_flags": "-dummy-compiler",
"diff_flags": {},
"decompiler_flags": "-decompiler",
"libraries": [],
"num_scratches": 0,
"owner": {
"is_anonymous": false,
"id": 2,
"is_online": true,
"is_admin": false,
"username": …
```

feat(presets): include profile in preset owner field

---

frontend/src/components/Diff/DragBar.module.scss

8px matches the size of the vertical dividers.

Make it a little easier to move target/current diff divider on mobile

---

backend/Dockerfile
backend/coreapp/platforms.py

SOTN uses a Metrowerks compiler that seems to emit the same sort of debug info as the PS2 compilers. This commit changes the binutils to use the modified PS2 binutils. From what I see locally it seems to work fine.

Use modified PS2 binutils for PSP

---

backend/compilers/compilers.linux.yaml
backend/coreapp/compilers.py
frontend/src/lib/i18n/locales/en/compilers.json

This already exists in [compilers](https://github.com/decompme/compilers/tree/main/platforms/gc_wii/mwcc_43_202), but appears to have been missed here.

Add mwcc_43_202 compiler (Wii MW 1.6)

---

backend/coreapp/serializers.py
backend/coreapp/tests/test_preset.py
backend/coreapp/views/user.py

When creating custom presets, the `/api/compiler` is including the presets for each platforms, however when serialiazing the owner field a KeyError is raised.
As visible in the code bellow, we are tyring to get the `request` from the context.
https://github.com/decompme/decomp.me/blob/294a2dc1b9fe1d6a033e07d88c92bf4a885d4769/backend/coreapp/serializers.py#L56-L58
However, in this specific context (serialiazing the owner field of a custom preset we include for a platform), it is not available. 
We can clearly notice however that the `serialize_profile` function is not using the request argument we are sending, it uses the `profile` only. Therefore an easy fix is to remove the request.

fix: profile field serialization in compiler view

---

backend/coreapp/platforms.py

Force including prelude requires -Fi, as it was it just tries to assemble prelude

Fixes invoking JWasm

---

backend/coreapp/sandbox.py

Attempt to fix:
```
Compiler error: /tmp/object.o
pwd is /tmp
CCPSX 3.06.0015 (Win32, PSX version 3.02)
Error - could not create temporary file 'C:\users\ethteck\Temp\PQ2'
```
Might work. Probably wont. I hate CCPSX.

Try creating 'Temp' dir for wine

---

backend/coreapp/compilers.py
frontend/src/lib/i18n/locales/en/compilers.json

It doesn't work for:
- the DOS compilers like 3.3/3.5.3/6 (I couldn't figure it out)
- PSYQ4.0 (error executing CCPSX.EXE)
- PSYQ4.3 (there is no CCPSX.EXE, will need to update the download link / Docker image)

Switch a few PSYQ compilers to use CCPSX.EXE

---

backend/coreapp/platforms.py

With the recent gp_rel workaround added to splat (`use_gp_rel_macro_nonmatching: False`) previous `addiu $rt, $gp, SYMBOL` instructions are now `la $rt, (SYMBOL)`, this pseudo expands to `daddiu $rt, $gp, SYMBOL` when the ABI is set to eabi, which is not what it expanded to with the original assemblers.
This PR removes the ABI flag so the pseudo expands to the more appropriate encoding,

Remove abi flag from PS2 assemble_cmd

---

frontend/src/components/Sort.tsx

Resolves #1298 
Swapped the compare functions associated with `LEAST_MATCHED` and `MOST_MATCHED`. Ordering appears correct now, this is from my local version with the change:
This should also address the same pattern I was noticing when implementing a frontend sort for #1249. I can put a PR in for that as soon as this is resolved!

1298: Swap least and most compare fns

---

frontend/package.json
frontend/src/components/Scratch/ScratchToolbar.tsx
frontend/src/components/Scratch/panels/AboutPanel.tsx
frontend/src/components/ScratchList.tsx
frontend/src/components/TimeAgo.tsx
frontend/src/components/TimeAgo2.tsx
frontend/yarn.lock

Friendly hovertext for TimeAgo

---

frontend/yarn.lock

No meaningful change, just removes the warning when starting up
```
root@b94fba06266c:/frontend# npx update-browserslist-db@latest
Need to install the following packages:
update-browserslist-db@1.1.0
Ok to proceed? (y) y
Latest version:     1.0.30001660
Installed version:  1.0.30001599
Removing old caniuse-lite from lock file
Installing new caniuse-lite version
$ yarn add -W caniuse-lite
warning " > ansi-to-react@6.1.6" has incorrect peer dependency "react@^16.3.2 || ^17.0.0".
warning " > ansi-to-react@6.1.6" has incorrect peer dependency "react-dom@^16.3.2 || ^17.0.0".
warning "next-pwa > babel-loader@8.3.0" has unmet peer dependency "@babel/core@^7.0.0".
warning " > use-persisted-state@0.3.3" has incorrect peer dependency "react@^16.8.0 || ^17.0.0".
Cleaning package.json dependencies …
```

Bump update-browserslist-db 'Browserslist: caniuse-lite is outdated'

---

frontend/src/components/Diff/Diff.tsx
frontend/src/components/Diff/DiffRowAsmDiffer.tsx
frontend/src/components/Diff/DiffRowObjdiff.tsx
frontend/src/components/Scratch/Scratch.tsx
frontend/src/components/ScrollContext.tsx

Leaned heavily on #1236.
Kinda related to #423.
Tested (via vercel) to be working for asm-differ and objdiff diffs :+1:

Scroll to source line on diff click

---

frontend/src/components/Diff/Diff.module.scss
frontend/src/components/Diff/Diff.tsx

It's working, but it needs some toast or anything instead of the alert.

Implement ASM Diff contents Copy Button

---

frontend/src/components/Scratch/ScratchToolbar.module.scss
frontend/src/components/Scratch/ScratchToolbar.tsx

This pull request includes changes to the `ScratchToolbar` component to improve the user experience by allowing the scratch name to be highlighted and copied.
Improvements to user experience:
* [`frontend/src/components/Scratch/ScratchToolbar.module.scss`](diffhunk://#diff-91431468f8d5c4d3be20016d8821f41b2c1945a4dfa9ce4957b044e7bc19f95aR179-R184): Added a new CSS class `.scratchName` to enable text selection and cursor indication for the scratch name.
* [`frontend/src/components/Scratch/ScratchToolbar.tsx`](diffhunk://#diff-1409658d54045b7b96096e2e6a348556ad8c6763a3b9e237d188d81c783d3110L118-R118): Updated the `ScratchName` component to use the new `.scratchName` class, allowing the scratch name to be highlighted and copied.
Fixes #1354

Allow scratch name to be highlighted and copied for non-owners

---

backend/coreapp/views/scratch.py

Display error message when trying to decompile a scratch created via object file

---

backend/coreapp/compilers.py
frontend/src/components/Scratch/Scratch.tsx
frontend/src/lib/codemirror/pascal.d.ts
frontend/src/lib/codemirror/pascal.js

- This PR adds minimal support for the Pascal language to mostly highlight some keywords and types.
- Note that this was mostly implemented to support SGI Pascal (the Pascal extension that IDO uses) and not common modern dialects like Free Pascal or Delphi.

Initial support for Pascal syntax

---

backend/coreapp/views/scratch.py
docs/CONTRIBUTING.md

This changes the family tab of scratches created via objdiff to filter out scratches that target another diff label in the same object. This fixes the bug where objdiff scratches would always show scratches for unrelated functions in the family tab and the "This function has been matched" header bar at the top.
Fixes #1281 and https://github.com/encounter/objdiff/issues/77
Note: I only tested this very briefly on a local database, it seems to get the right behavior on the object I tested but I can't test on the live database.

Fix scratches being grouped into the same family even if targeting different functions in the same object

---

backend/compilers/compilers.darwin.yaml
backend/compilers/compilers.linux.yaml
backend/coreapp/compilers.py
frontend/src/lib/i18n/locales/en/compilers.json

This has some new features over the stock version (e.g. anonymous unions) which we'd like to use for OoT iQue. I managed to test this locally but I don't really know what I'm doing here
Compiler added in https://github.com/decompme/compilers/pull/26
Fixes #1402

Add decompals fork of EGCS 1.1.2-4

---

.github/workflows/ci.yml
backend/Dockerfile
backend/compilers/compilers.linux.yaml
backend/coreapp/asm_preludes/msdos.s
backend/coreapp/compilers.py
backend/coreapp/diff_wrapper.py
backend/coreapp/flags.py
backend/coreapp/platforms.py
backend/poetry.lock
frontend/src/lib/i18n/locales/en/compilers.json

Depends on
https://github.com/simonlindholm/asm-differ/pull/178
https://github.com/decompme/compilers/pull/28

[WIP] Add Borland 3.1 compiler to MS-DOS platform

---

backend/coreapp/compilers.py

The gist of this PR is that we now tell dosemu2 to mount the **current directory** (i.e. `/tmp` within the sandbox) as the `D:` drive (NOTE: The borland compiler mounted the `$COMPILER_DIR` as `D:` so that is a slightly different approach). 
This means we can *start* in the `${COMPILER_DIR}` using the `-K` and give relative paths to the executables we need to run, *and* give precise paths to the files we want to compile (i.e. `D:\\input.c`)
I couldn't solve #1422 entirely, there is still 1 compiler that requires us to `cp -r` the files from COMPILER_DIR into the sandbox

Copy a bit less stuff when using dosemu

---

backend/Dockerfile
docker-compose.yaml

Just install all packages/requirements by default. The downloading of compilers is still managed via the environment vars (i.e. clang is disabled by default), so this just keeps things simple.

Simplify backend dockerfile

---

backend/coreapp/diff_wrapper.py

Rather than just showing this error in the UI
```
Diff error: Error running asm-differ: invalid literal for int() with base 0: ' lr}'
```
Show this in the server logs too to help pinpoint the failure:
```
backend-1   | 09:27:36 ERROR Error running asm-differ: invalid literal for int() with base 0: ' lr}'
backend-1   | Traceback (most recent call last):
backend-1   |   File "/backend/coreapp/diff_wrapper.py", line 295, in diff
backend-1   |     result = DiffWrapper.run_diff(basedump, mydump, config)
backend-1   |   File "/backend/coreapp/diff_wrapper.py", line 249, in run_diff
backend-1   |     base_lines = asm_differ.process(basedump, config)
backend-1   |   File "/backend/virtualenvs/backend-yStQQXE7-py3.10/lib/python3.10/site-packages/diff.py", line 2908, in process
backend-1   | …
```

Add traceback in logs if asm-differ throws an Exception

---

backend/coreapp/compilers.py
frontend/src/lib/i18n/locales/en/compilers.json

Addresses #1445 for 2/3 of the prodg compilers.

Switch prodg 3.5 and 3.7 compilers to ngccc driver

---

backend/coreapp/models/profile.py

So, I believe that `last_request_date` only actually set on profile.save() ... and for the Yandex bot that trawls/executes javascript we create a generic profile but do not save it.

Add extra sanity check to user.is_online()

---

.github/workflows/ci.yml
backend/Dockerfile
backend/coreapp/compiler_wrapper.py
backend/coreapp/compilers.py
backend/coreapp/sandbox.py
docker-compose.yaml

**Notes**
- This PR also cleans up `ci.yaml`, bringing it more in-line with the steps in the Dockerfile
- For some reason calling `cpp` (`which cpp` tells me its `/bin/cpp`) gives a different behaviour to calling `/usr/bin/cpp` (which is the same binary) - it tries to execute system `cc1` (it is ignoring the -E arg completely). Giving the full path to `cpp` corrects this weirdness.
**Known Issues:**
**Appendix**
Demonstrating the dumbness of `cpp`:
```
ubuntu@f21440c3d414:/backend$ ls -al /usr/bin/cpp
lrwxrwxrwx 1 root root 6 Jan 31  2024 /usr/bin/cpp -> cpp-13
ubuntu@f21440c3d414:/backend$ ls -al /bin/cpp
lrwxrwxrwx 1 root root 6 Jan 31  2024 /bin/cpp -> cpp-13
ubuntu@f21440c3d414:/backend$ ll /usr/bin/cpp-13
lrwxrwxrwx 1 root root 23 Sep  4 14:44 /usr/bin/cpp-13 -> …
```

Ubuntu 24.04

---

frontend/src/app/(navfooter)/new/NewScratchForm.tsx

Also align the "or" to be between the two select inputs as it's always bugged me that it's in the middle of the whole div.

Don't auto select 1st preset for platform on /new

---

frontend/src/app/(navfooter)/platform/[id]/page.tsx
frontend/src/app/(navfooter)/preset/[id]/page.tsx
frontend/src/components/PresetList.tsx

We have some presets with thousands of scratches, so stick a `,` in the number to avoid `3596` like below:

Stick thousands separators in num_scratches on preset page

---

backend/coreapp/views/preset.py

I need someone with a bigger brain to confirm whether this is better or not.
```py
$ /home/ethteck/.local/bin/poetry run ./manage.py shell
Python 3.12.3 (main, Jan 17 2025, 18:03:48) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from django.apps import apps
>>> Preset = apps.get_model("coreapp", "Preset")
>>> from django.db.models import Count
>>> print(Preset.objects.all().annotate(num_scratches=Count("scratch")).explain())
HashAggregate  (cost=24066.05..24067.67 rows=162 width=187)
Group Key: coreapp_preset.id
->  Hash Right Join  (cost=8.64..23344.52 rows=144306 width=184)
Hash Cond: (coreapp_scratch.preset_id = coreapp_preset.id)
->  Seq Scan on coreapp_scratch  (cost=0.00..22951.06 rows=144306 width=13)
->  Hash …
```

Optimise Preset's num_scratches annotation

---

backend/coreapp/compilers.py

I couldn't manage to inject anything into the COMPILER_FLAGS to invoke any bad behaviour.

Allow -x flag to be passed to GCC PS1 compilers again

---

frontend/src/app/(navfooter)/privacy/page.tsx

Opening this as a PR for a bit and will merge if no one has any issues. This isn't much of a change in policy other than to remove the notion we won't share data with "third parties" because it's ambiguous what a third party would be, and it's also untrue that people not associated with the site should be able to access site data. 
For example, researchers wanting to improve decompilers by looking at the scratch database could easily be considered a third party, but this is also a totally valid use case for handling site data.
To reiterate, all  the data we're talking about is already publicly available on the site, visually and through the API. Nothing about the data in question involves private user info, authentication tokens, or anything of that nature.

Update privacy policy

---

frontend/src/components/Diff/ObjdiffPanel.tsx

Fixes context menu -> copy in the experimental objdiff integration.

objdiff: allow="clipboard-write"

---

backend/compilers/compilers.linux.yaml
backend/coreapp/compilers.py
backend/coreapp/migrations/0058_rename_gcc272sn_to_gcc272sn0004.py
frontend/src/lib/i18n/locales/en/compilers.json

This adds 2 previously lost SN 2.7.2 versions and their C++ versions, totalling 4 new compilers for the N64. The previous version of SN 2.7.2 has also been renamed to reflect its build compared to these builds. Note that for build 0001 to work, a recently updated `psyq-obj-parser` is needed to handle the GP relocations. The cygnus builds (0004/6) disable `-G` by default and even seem to block its usage, so `-G0` seems fine to use for them.
Also note that the compilers currently have no download links, this should be updated once they have a home.

Add 4 new versions of SN 2.7.2 for Nintendo 64

---

frontend/src/app/(navfooter)/credits/page.tsx
frontend/src/app/(navfooter)/settings/appearance/AppearanceSettings.tsx
frontend/src/app/(navfooter)/settings/appearance/ExampleCodeMirror.tsx
frontend/src/app/ThemeProvider.tsx
frontend/src/app/globals.scss
frontend/src/components/Diff/ObjdiffPanel.tsx
frontend/src/lib/settings.ts

This pulls in [JetBrains Mono](https://www.jetbrains.com/lp/mono/) as a variable web font (2 KiB) and uses it as the default font family. The default size is updated from 11px to 13px to improve legibility.
Additionally, an appearance setting "Enable ligatures" is added, allowing users to disable the font ligatures that are included in JetBrains Mono (or their own configured font).
<p align="center">Before / After (Appearance Settings)</p>
<p align="center">
</p>
<p align="center">Before / After (Scratch)</p>
<p align="center">
</p>
Note that my default `monospace` font is configured to `Noto Sans Mono`, which is similar to JetBrains Mono, so you won't see much difference in the font in these comparisons. It will be more apparent if the monospace font is not configured at a system level. …

Update default font & increase size

---

frontend/src/app/(navfooter)/settings/appearance/AppearanceSettings.tsx
frontend/src/app/ThemeProvider.tsx

I researched the values of `font-variant-ligatures` a little more and determined that this is more precise: since we apply this property to the whole page, we don't want to disable _all_ ligatures, which can be used by the UI font for legibility purposes. Specifically, the contextual (or `calt`) ligatures are what we want to enable/disable, so this makes it explicit.
Additionally, Safari doesn't seem to support the contextual ligatures, so I modified the setting description slightly to avoid confusion.

Adjust `font-variant-ligatures` usage

---

frontend/src/app/(navfooter)/settings/appearance/AppearanceSettings.tsx
frontend/src/app/(navfooter)/settings/appearance/page.tsx
frontend/src/app/(navfooter)/settings/editor/page.tsx

SSR causes weird behavior on the settings pages: it will populate the page with the default values, and _only in some cases_ actually hydrate the client's settings values once loaded. This only happens if you navigate to one of these pages directly, or refresh while you're on one of the pages.
This causes errors in development mode too: if you navigate to `/settings/appearance` in dev mode, change the font size and refresh, you'll get an error about the SSR/client hydration mismatch.
This solution is outlined in the [Next.js documentation](https://nextjs.org/docs/messages/react-hydration-error#solution-2-disabling-ssr-on-specific-components) for that error.

Disable SSR for settings pages

---

backend/coreapp/compiler_wrapper.py
backend/coreapp/compilers.py
backend/coreapp/m2c_wrapper.py

This way the fact that the type can be only one of the three is better represented. Alternatively we could also check isinstance(compiler, IDOCompiler), etc.

Refactor compilers in the backend

---

backend/coreapp/views/preset.py

the `owner` field throws an `icontains` error (similar to [this](https://stackoverflow.com/questions/76406530/i-am-getting-this-error-django-core-exceptions-fielderror-unsupported-lookup-i)),need to be more specific and pick the username field.
screenshot from local testing:

Bugfix API 'preset?search=xxx' behaviour

---

backend/coreapp/sandbox.py

The backend crashed on a scratch timeout (it was a Saturn scratch which invokes dosemu2). The crashed happened due to the sandbox cleanup function erroring. Not sure why?
More info at https://decompme.sentry.io/issues/6578749636?project=4504592976904192.

Ignore errors when cleaning up sandbox

---

frontend/src/lib/codemirror/useCompareExtension.ts

This is a slight band-aid for #1538. The issue of unnecessary horizontal scrollbars won't occur when there is no parent scratch to compare the current scratch / context to.

Fast return from useCompareExtension when compareTo is undefined

---

frontend/src/app/(navfooter)/new/NewScratchForm.tsx
frontend/src/components/PlatformSelect/PlatformSelect.tsx
frontend/src/components/compiler/CompilerOpts.tsx
frontend/src/lib/api.ts

This PR rewrites the core of the scratch creation form from the ground up.
Key changes:
1. (unchanged) The form receives the list of available platforms via props.
2. On load, it checks local storage for a previously selected platform. If it's valid, it's used; otherwise, the first available platform is selected.
3. It then fetches the compilers and presets for the selected platform.
4. If a valid presetId is found in local storage, it sets the compiler, flags, and libraries accordingly.
5. If no valid preset is found, it checks for a stored compilerId and uses it if valid.
6. If no valid compiler is found, the first available compiler is selected.
Since users can't manually configure compiler flags, diff flags, or libraries when creating a scratch, there's no need to persist these in …

Rewrite NewScratchForm

---

backend/coreapp/migrations/0059_scratch_family_alter_scratch_parent.py
backend/coreapp/migrations/0060_populate_scratch_family.py
backend/coreapp/models/scratch.py
backend/coreapp/views/scratch.py

The idea here is to avoid the N+1 query when trying to find related scratches. We keep track of the ultimate parent of each scratch upon creation/forking so that it's a simple lookup to find the family.
If the ultimate parent scratch gets deleted, then we'll fall back to using the immediate parent of the scratch. I think this is a fair trade-off in terms of usability vs performance; ideally people don't delete family scratches if they're interested in tracking the family.

Add 'family' slug to track ultimate ancestor for a Scratch

---

frontend/src/lib/api.ts

Query takes ~100ms because it's doing an accurate .count() on 3 tables, bumping to 60 second refresh (currently 5). We can revisit this as/when we move to an 'activity log' (which ideally would be websocket rather than a poll)

Refresh stats every 60s

---

backend/coreapp/tests/test_scratch.py
backend/coreapp/views/scratch.py

API requests are made by the frontend with no-cache (and no explicit etag handling). Remove the etag functionality from the backend - we can always add it back another day.

Remove unused etag behaviour

---

.github/workflows/ci.yml
backend/Dockerfile

Already updated prod:
```bash
$ mkdir /tmp/omf
$ cd /tmp/omf
$ wget "https://github.com/decompals/binutils-omf/releases/download/v0.4/omftools-linux-x86_64.tar.gz"
$ sudo tar xvzf omftools-linux-x86_64.tar.gz -C /usr/bin omf-nm omf-objdump
[sudo] password for mark: 
omf-nm
omf-objdump
```

Bump binutils-omf to 0.4

---

backend/coreapp/serializers.py
backend/coreapp/views/scratch.py
backend/coreapp/views/user.py

Ensure we prefetch the github user (via user) to avoid this craziness:

Fix N+1 scratch list

---

frontend/src/components/compiler/CompilerOpts.tsx

On the live site you can only add/remove a library if a scratch already has a library set (i.e. via the preset). This isn't great, so change it so we will show available libraries if we have any for the given platform.

Fix missing library section

---

backend/coreapp/middleware.py
frontend/src/lib/api.ts

Given we treat a user as "online" if they've done something in the last 2 minutes, it seems excessive to update their `last_updated_date` so often (especially as *every* API request will update the time)
Also tweak the presets to refresh every 5 minutes, hitting F5 or a fresh navigation to the site will clear all SWR cache anyway, so I don't think anyone will notice :)

Tweak last updated

---

backend/coreapp/libraries.py

3/3 of the libraries on the site use the `include` directory, and we explicitly check that it exists in order to determine if a library is available.
- dx5 https://github.com/roblabla/directx-headers/tree/5.0/include
- dx8 https://github.com/roblabla/directx-headers/tree/main/include
- dx9 https://github.com/ifarbod/dxsdk9/tree/master/include

Append 'include' dir to a library's include_dir

---

frontend/Dockerfile.prod

closes #1586.
This one *isn't* baked into the build, but is taken from the runtime environment.
TODO later: just bake this into the build.

GIT_HASH is a server-side environment variable

---

.github/workflows/ci.yml
backend/decompme/settings.py

Looking in sentry the typical (p75/p99) time to `connect()` from django to postgres is ~16ms. This seems high given both containers are on the same box, but there we go. Django allows connections to be reused (rather than closed at the end of each request which is the default behaviour), so I think we should give that a go and it should give a small (but effectively free) performance boost for every request made.
Will need the `docker.prod.env` file updated.

Expose configuration to allow db connections to be reused

---

nginx/production.conf

Tweak the buffers a little bit. This scratch sends the client a 800kb response to POST-ing `/compile`. So try and hold it in memory rather than writing to disk. Might need further tweaks, we shall see.
```
2025/06/10 07:11:24 [warn] 31#31: *57206 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000002145, client: 162.158.166.228, server: decomp.me, request: "POST /api/scratch/kGIDp/compile HTTP/2.0", host: "decomp.me", referrer: "https://decomp.me/scratch/kGIDp"
2025/06/10 07:11:26 [warn] 31#31: *57206 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000002146, client: 162.158.166.228, server: decomp.me, request: "POST /api/scratch/kGIDp/compile HTTP/2.0", host: "decomp.me", referrer: "https://decomp.me/scratch/kGIDp" …
```

Allow 512k in-flight before buffering data to disk

---

nginx/production.conf

Per title. [HMR](https://webpack.js.org/concepts/hot-module-replacement/) is a development thing (for live edits).
I copy/pasted the nginx configuration block from the dev docker setup without much thought. and have subsequently engaged my brain...

Hot Module Replacement is a dev-only thing

---

frontend/src/components/Breadcrumbs.tsx

Kinda moot because we only use breadcrumbs in the scratch toolbar, and the final items isnt a link (it's the editable scratch name)... but this clears the next.js warnings.

Remove legacyBehavior from Breadcrumbs Link

---

backend/coreapp/serializers.py
backend/coreapp/views/scratch.py

This PR fixes iFarbod's issue and closes out #1684.
...by the time we get to this line, `data["libraries"]` will already be a list of Library objects.
Once merged users can specify a preset that has libraries or alternatively manually select the libraries... something like:
```py
with open(target_o, "rb") as f:
data = {
"platform": "win32",
"compiler": "msvc6.0",
"context": "",
"source_code": "",
"libraries": json.dumps([{"name": "directx", "version": "9.0"}]),
}
files = {
"target_obj": ("target.o", f),
}
res = requests.post(
f"{DECOMPME_URL}/api/scratch",
files=files,
data=data,
)
```

Fix 500 when creating scratches with a preset that have libraries
