decompme/decomp.me

- frontend/src/api.js
- frontend/src/scratch/Scratch.jsx
- frontend/src/scratch/Scratch.module.css
> front: show diff and logs

- .gitignore
- frontend/package.json
- frontend/postcss.config.js
- frontend/src/App.jsx
- frontend/src/ExpandToggle.module.css
- frontend/src/Select.jsx
- frontend/src/Select.module.css
- frontend/src/global.css
- frontend/src/hooks.js
- frontend/src/index.jsx
- frontend/src/scratch/CompilerConfigSelect.jsx
- frontend/src/scratch/Editor.jsx
- frontend/src/scratch/Editor.module.css
- frontend/src/scratch/NewScratch.jsx
- frontend/src/scratch/NewScratch.module.css
- frontend/src/scratch/Scratch.jsx
- frontend/src/scratch/Scratch.module.css
- frontend/src/scratch/c.js
- frontend/src/scratch/monacoTheme.json
- frontend/yarn.lock
> restyle whole site

- docker-compose.yaml
> Add missing capability to support sandbox jail in Docker

- backend/asm_differ/.gitrepo
- backend/asm_differ/.pre-commit-config.yaml
- backend/asm_differ/README.md
- backend/asm_differ/diff.py
- backend/mips_to_c/.gitrepo
- backend/mips_to_c/src/c_types.py
- backend/mips_to_c/tests/end_to_end/complicated_context/orig.c
Updates mips_to_c and asm_differ
> Subrepo update

- backend/asm_differ/.gitrepo
- backend/asm_differ/README.md
- backend/asm_differ/diff-stylesheet.css
- backend/asm_differ/diff.py
- backend/asm_differ/diff_settings.py
- backend/asm_differ/mypy.ini
- backend/coreapp/asm_diff_wrapper.py
- backend/coreapp/views.py
- frontend/src/api.ts
- frontend/src/scratch/Scratch.module.css
- frontend/src/scratch/Scratch.tsx
This PR what I'd call the bare minimum to switch from the `asm_differ`'s `HtmlFormatter` to the `JsonFormatter`. 
I'm not very familiar with JSX -- so please critique the style/conventions there.
I'll leave some comments inline on the sections that are particularly *weird*.
> Use JSON format from asm_differ

- backend/coreapp/urls.py
- backend/coreapp/views.py
Not referenced on the frontend at all, mostly exists as a proof-of-concept for building a `.zip` file dynamically from the files in the database.
> Add /export endpoint for downloading .zip

- backend/Dockerfile
- backend/coreapp/sandbox.py
- backend/requirements.txt
Couldn't see anything breaking without it, so away it goes...
> Remove /lib32 mount

- backend/asm_differ/.gitrepo
- backend/asm_differ/diff.py
subrepo:
merged:   "89df9d7"
upstream:
commit:   "89df9d7"
git-subrepo:
origin:   "git@github.com:ingydotnet/git-subrepo.git"
> update asm-differ to latest

- frontend/src/components/compiler/PresetSelect.tsx
> add -inline auto to Pikmin 2 preset

- frontend/src/components/compiler/PresetSelect.tsx
Same as Super Monkey Ball Preset but with GC MW 1.2.5e compiler instead. (and extended args)
> Add Super Smash Bros. Melee Preset

- .gitattributes
- .github/workflows/pr.yml
- backend/compilers/download.sh
- backend/compilers/mwcc.sh
- backend/compilers/mwcc_233_144/config.json
- backend/compilers/mwcc_233_159/config.json
- backend/compilers/mwcc_233_163/config.json
- backend/compilers/mwcc_233_163e/config.json
- backend/compilers/mwcc_242_81/config.json
- backend/compilers/mwcc_247_105/config.json
- backend/compilers/mwcc_247_107/config.json
- backend/compilers/mwcc_247_108/config.json
- backend/compilers/mwcc_247_108_tp/config.json
- backend/compilers/mwcc_247_92/config.json
- backend/compilers/mwcc_41_60126/config.json
- backend/compilers/mwcc_41_60831/config.json
- backend/compilers/mwcc_42_142/config.json
- backend/compilers/mwcc_43_151/config.json
- backend/compilers/mwcc_43_172/config.json
- backend/compilers/mwcc_43_213/config.json
- backend/compilers/psyq4.1/config.json
- backend/compilers/psyq4.3/config.json
- backend/compilers/psyq4.6/config.json
- backend/coreapp/compiler_wrapper.py
- backend/coreapp/tests.py
Tested under linux, need to reboot and test under WSL :+1:
> Skip wine if WSL environment detected

- frontend/src/components/ErrorBoundary.module.scss
- frontend/src/components/ErrorBoundary.tsx
- frontend/src/components/Footer.tsx
- frontend/src/components/Layout.tsx
- frontend/src/components/Nav/LoginState.tsx
- frontend/src/components/Nav/Nav.tsx
This should make the UI more resilient to errors
> Add ErrorBoundary

- backend/coreapp/asm_diff_wrapper.py
> Better parsing of start_address from nm output

- backend/coreapp/compiler_wrapper.py
- backend/coreapp/tests.py
- backend/coreapp/views/scratch.py
- frontend/src/lib/api.ts
- frontend/src/pages/scratch/new.tsx
Fixes #251, fixes #235, fixes #224
> Actually return errors for compile errors

- backend/coreapp/asm_diff_wrapper.py
- backend/coreapp/middleware.py
- backend/coreapp/serializers.py
- backend/coreapp/tests.py
- backend/coreapp/views/scratch.py
- frontend/src/components/ScoreBadge.tsx
- frontend/src/lib/api.ts
- frontend/src/pages/scratch/[slug].tsx
> Prevent profiles being created for SSR requests, serializer cleanup

- frontend/src/components/ScoreBadge.tsx
- frontend/src/components/Scratch/ScratchToolbar.tsx
- frontend/src/pages/scratch/[slug].tsx
Don't show score of -1, always show compile button, fix ssr compilations
> User Feedback

- frontend/src/components/Scratch/ScratchToolbar.tsx
- frontend/src/components/Scratch/buttons/SaveScratchButton.tsx
- frontend/src/components/Scratch/hooks/useFuzzySaveCallback.ts
- show loading state on save button when shortcut used
- change compile shortcut to ctrl+j
> Minor frontend fixes

- frontend/src/components/compiler/PresetSelect.tsx
I'm a lazy man, and constantly forget to change my options, so this makes it easier for me (and hopefully others!)
> Add Diddy Kong Racing to presets

- backend/asm_differ/.gitrepo
- backend/asm_differ/diff.py
subrepo:
merged:   "6f8f80b"
upstream:
commit:   "6f8f80b"
git-subrepo:
origin:   "git@github.com:ingydotnet/git-subrepo.git"
> Pulling latest asm-differ

- .github/workflows/pr.yml
- frontend/package.json
- frontend/src/components/Nav/Search.tsx
- frontend/src/components/Nav/UserMenuItems.tsx
- frontend/src/components/Scratch/ScratchToolbar.tsx
- frontend/src/lib/api.ts
- frontend/src/pages/_app.tsx
- frontend/src/pages/index.tsx
- frontend/src/pages/login.tsx
- frontend/src/pages/new.tsx
- frontend/yarn.lock
- add next-plausible
- add analytics events to key actions
> Add plausible analytics to frontend

- backend/compilers/ido5.3/config.json
- backend/compilers/ido7.1/config.json
- backend/coreapp/compiler_wrapper.py
- backend/coreapp/tests.py
- frontend/src/components/compiler/PresetSelect.tsx
- frontend/src/components/compiler/compiler_settings/ido.tsx
Reverts decompme/decomp.me#335
> Revert "Support -KPIC for IDO"

- .github/workflows/pr.yml
> Fix dog (round 3)

- backend/compilers/clang-3.9.1/config.json
- backend/compilers/clang-4.0.1/config.json
- backend/compilers/clang.sh
- frontend/src/components/compiler/PresetSelect.tsx
- frontend/src/components/compiler/compiler_settings/clang.tsx
A set of small fixes to Clang for Switch support.
> Clang fixes

- frontend/package.json
- frontend/src/components/Diff/Diff.tsx
- frontend/yarn.lock
Allows Clang's pretty color diagnostics to show up correctly
> frontend: Translate ANSI color codes to HTML colors

- frontend/src/components/compiler/PresetSelect.tsx
As the title of the PR suggests.
> Add Castlevania SOTN preset

- backend/coreapp/asm_diff_wrapper.py
- backend/coreapp/compiler_wrapper.py
- backend/coreapp/tests.py
- backend/coreapp/views/scratch.py
Also do some refactoring, make it so scratches don't update when we update their score/max_score
fixes #357
> Make max_score populate even if the compilation fails

- backend/coreapp/compiler_wrapper.py
> Filter meaningless wine errors (whining)

- backend/asm_differ/.gitrepo
- backend/asm_differ/diff.py
subrepo:
merged:   "64b58ab"
upstream:
commit:   "64b58ab"
git-subrepo:
origin:   "git@github.com:ingydotnet/git-subrepo.git"
> git subrepo pull --force backend/asm_differ

- backend/coreapp/compilers.py
- backend/coreapp/views/compilers.py
- frontend/src/components/compiler/CompilerOpts.tsx
- frontend/src/components/compiler/PresetSelect.tsx
- frontend/src/lib/api.ts
- frontend/src/pages/new.tsx
so all presets of a platform are visible at once
also refactors the api a smidge
> Fix preset selection regression

- frontend/src/components/Diff/CompilationPanel.tsx
- frontend/src/components/Diff/Diff.module.scss
- frontend/src/components/Diff/Diff.tsx
- frontend/src/components/Editor/CodeMirror.tsx
- frontend/src/components/Scratch/Scratch.tsx
- frontend/src/components/Scratch/renderTabs.tsx
- frontend/src/lib/api.ts
This could really use a good code review from someone who knows react.
> Highlight assembly line on source selected line change

- frontend/src/components/Diff/Diff.module.scss
- frontend/src/components/Diff/Diff.tsx
- frontend/src/components/Editor/CodeMirror.tsx
- frontend/src/components/Scratch/ScratchPreferencesModal.tsx
- frontend/src/components/Scratch/renderTabs.tsx
- frontend/src/lib/settings.ts
- frontend/src/pages/_app.scss
- configurable code font size
- configurable diff font size
> Configurable font size

- frontend/package.json
- frontend/src/components/Diff/Diff.tsx
- frontend/src/components/Editor/CodeMirror.tsx
- frontend/src/components/Scratch/ScratchDecompileModal.tsx
- frontend/src/components/Scratch/renderTabs.tsx
- frontend/src/lib/codemirror/basic-setup.ts
- frontend/src/lib/codemirror/default-keymap/README.md
- frontend/src/lib/codemirror/default-keymap/indent.ts
- frontend/src/lib/codemirror/default-keymap/index.ts
- frontend/src/lib/codemirror/default-keymap/multiCursor.ts
- frontend/src/lib/codemirror/default-theme.ts
- frontend/src/pages/_app.scss
- frontend/src/pages/new.tsx
- frontend/src/pages/scratch/[slug].tsx
- frontend/yarn.lock
- increase vertical diff padding
- improve codemirror extensions
- remove scratch state debouncer
- update codemirror theme
> CodeMirror extension changes

- .github/workflows/pr.yml
- backend/Dockerfile
- backend/coreapp/compilers.py
- backend/coreapp/tests.py
- frontend/src/components/PlatformSelect/macos9.svg
Fixes issues that arose with the mwcppc compiler after the previous pr was merged and deployed.
> Fix errors with deployment

- backend/compilers/download.py
Updates the asm conversion script to fix some issues I encountered.
> Update download link for MWCPPC

- backend/asm_differ/.gitrepo
- backend/asm_differ/diff.py
asm differ update includes fixes to ppc sda21 relocations
> Updated asm-differ submodule

- backend/asm_differ/.gitrepo
- backend/asm_differ/diff.py
subrepo:
merged:   "87029d0"
upstream:
commit:   "87029d0"
git-subrepo:
origin:   "https://github.com/ingydotnet/git-subrepo"
> update asm-differ submodule

- backend/asm_differ/.gitrepo
- backend/asm_differ/diff.py
Make imm_matches_everything only process row args, exclude the mnemonic
> update asm_differ module

- backend/asm_differ/.gitrepo
- backend/asm_differ/diff.py
subrepo:
merged:   "6a7834b"
upstream:
commit:   "6a7834b"
git-subrepo:
origin:   "https://github.com/ingydotnet/git-subrepo"
> update asm differ submodule

- backend/asm_differ/.gitrepo
- backend/asm_differ/diff.py
git subrepo pull --force backend/asm_differ
subrepo:
merged:   "93441f6"
upstream:
commit:   "93441f6"
git-subrepo:
origin:   "https://github.com/ingydotnet/git-subrepo"
> Update Asm-differ module

- backend/coreapp/compilers.py
> Add MGS PS1 preset

- backend/compilers/download.py
- backend/coreapp/models/github.py
> Grab new github username on login

- frontend/src/components/Diff/CompilationPanel.module.scss
- frontend/src/components/Diff/CompilationPanel.tsx
> Hide compilation issues panel

- backend/asm_differ/.gitignore
- backend/asm_differ/.gitrepo
- backend/asm_differ/diff.py
Finally GCC decomp will have all its arrows.
> asm-differ update: J arrows support

- backend/coreapp/urls.py
- backend/coreapp/views/stats.py
- frontend/src/lib/api.ts
- frontend/src/pages/index.module.scss
- frontend/src/pages/index.tsx
Fixes #145
Wasn't sure how to query the number of compilations
> Add stats to homepage

- .github/workflows/ci.yml
- backend/coreapp/compilers.py
I guess this won't kick in until it's merged?
> Ensure nsjail is enabled in CI for Docker

- backend/coreapp/models/github.py
- backend/coreapp/views/project.py
- frontend/src/components/GitHubLoginButton.tsx
- frontend/src/components/PrScratchBasket.tsx
- frontend/src/lib/oauth.ts
- frontend/src/pages/login.tsx
- remove public_repo requirement for login
- request public_repo on pull request create if needed
> Only request public_repo GitHub scope when making a PR

- frontend/src/components/Diff/Diff.module.scss
- frontend/src/components/Editor/CodeMirror.module.scss
- frontend/src/components/Editor/CodeMirror.tsx
- frontend/src/lib/codemirror/default-theme.ts
- frontend/src/pages/_app.scss
- move CodeMirror styles to css module
- use overlay scrollbars in Diff and CodeMirror
This fixes an issue @pixel-stuck reported ([Discord thread](https://discord.com/channels/897066363951128586/1020104086462402570))
> Use overlay scrollbars in CodeMirror

- .gitignore
- backend/docker.dev.env
- docker-compose.yaml
added `docker.dev.env` to .gitignore so local changes won't accidentally get commited (need's `-f` to explicitly add the file)
> Move docker env vars from docker-compose.yaml to docker.dev.env

- frontend/src/components/Scratch/Scratch.tsx
- frontend/src/pages/_app.scss
Resolves #554 
Needs testing on an Android device pls
> Fix mobile viewport bugs

- backend/coreapp/compilers.py
We got it slightly wrong the first time around :slightly_smiling_face:
> Update Metroid Prime (USA) preset

- backend/compilers/download.py
- backend/coreapp/compilers.py
- backend/coreapp/flags.py
- frontend/locales/en/compilers.json
Courtesy of @Mr-Wiseguy .
I haven't been able to test this since it's a Linux binary, but everything apart from compilation seems to be okay. I'm not very satisfied with the download script part so I'd be grateful for any suggestions.
> Add custom-built cc1 for SN64

- backend/coreapp/compilers.py
Reverts decompme/decomp.me#578
https://discord.com/channels/897066363951128586/897075447534354462/1036494193540993025
> Revert "Switch PSYQ to use CCPSX instead of CC1PSX+ASPSX chain"

- frontend/src/components/ScoreBadge.tsx
> Round percentages between 99.99 and 100 down

- backend/compilers/download.py
- backend/coreapp/compilers.py
Reverts decompme/decomp.me#580
> Revert "(hopefully) fix macos9 compiler"

- frontend/.babelrc
- frontend/next.config.js
- frontend/package.json
- frontend/src/lib/codemirror/useCompareExtension.ts
- frontend/src/lib/codemirror/useCompareExtension.worker.ts
- frontend/yarn.lock
> Move logic of useCompareExtension to a Web Worker

- backend/asm_differ/.gitrepo
- backend/asm_differ/diff.py
- backend/asm_differ/diff_settings.py
- backend/coreapp/diff_wrapper.py
- backend/m2c/.gitrepo
- backend/m2c/src/translate.py
> m2c / asm-differ updates

- backend/coreapp/compilers.py
presets for twilight princess RELs and the dolphin lib
> add tp rel / dolphin presets

- backend/coreapp/compilers.py
These are the up-to-date compiler options I've been using for Battle for Bikini Bottom - optimization flags should be more accurate.
> Update Battle for Bikini Bottom preset

- backend/coreapp/compilers.py
These flags worked on all the decompiled functions from AC in the site, more might need to be added in the future if it's needed for other functions
> Add Animal Crossing preset

- backend/coreapp/middleware.py
- backend/coreapp/sandbox.py
- frontend/src/components/Diff/CompilationPanel.tsx
- frontend/src/components/ScoreBadge.tsx
Make logs more brief by hiding the PATH from compile commands 
Hopefully prevent the frontend server from making tons of anonymous profiles 
Add a scroll bar to the problems window
Restore the old look of ScoreBadge
> A few things

- backend/coreapp/compilers.py
We've been using the site for `pret/pmd_red` and I figured it would be good to finally add a preset.
> Add Pokemon Mystery Dungeon: Red Rescue Team preset

- backend/coreapp/compilers.py
This adds the preset for Ikachan 3ds.
> Add preset for Ikachan 3ds

- backend/coreapp/platforms.py
allows for ease-of-making-scratches for repos using @encounter 's macros
> support newer assembly macros for GCN/Wii

- frontend/src/app/(navfooter)/new/NewScratchForm.tsx
Slapped a `className="mt-2"` to the "Create scratch" AsyncButton.
> Added Margin top to 'Create Scratch' button

- frontend/src/components/Diff/CompilationPanel.tsx
> fix problems panel not scrolling far enough

- backend/coreapp/compilers.py
Renames the current one as REL, DOL Preset needs sdata2 size threshold to 4.
> Implement presets for Animal Crossing

- backend/coreapp/platforms.py
turns out I added the macros to mac osx last time
> actually add macros to gcn

- backend/coreapp/models/scratch.py
`_ZN6PlayerC2EP28IUsePlayerActionGraphBuilderP15IUsePlayerInputP23IUsePlayerInputArrangerP18IUsePlayerAnimatorP16IUsePlayerEffectP15IUsePlayerAudioP14IUsePlayerBindP19IUsePlayerCheckAreaP19IUsePlayerCollisionP29IUsePlayerCollisionPartsArrayP22IUsePlayerSnapWallInfoP30IUsePlayerCollisionCheckSphereP34IUsePlayerCollisionCheckSphereMoveP29IUsePlayerCollisionCheckArrowP26IUsePlayerFireBallLauncherST_P16IUsePlayerAttackP16IUsePlayerGetPosP28IUsePlayerBindEndParamGetterP21IUseCollisionPartsMtxP24IUsePlayerWaterFlowFieldP18IUsePlayerReactionPK26IUsePlayerWaterSurfaceInfoP21IUsePlayerStoneStatueP25IUsePlayerHipDropObserverP23IUsePlayerEventReceiverPK20IUsePlayerCharaQueryP16IUsePlayerHoldedPK23IUsePlayerWallClimbInfoPK14IUsePlayerFlagS1P_S1P_S1P_P24IUsePlayerWallClimbInputPK16IUsePlayerPushedPK26I …
> Diff label max size increase

- frontend/.babelrc
- frontend/next.config.js
- frontend/package.json
- frontend/src/lib/codemirror/useCompareExtension.ts
- frontend/src/lib/codemirror/useCompareExtension.worker.ts
- frontend/yarn.lock
Should close #712.
Strips out all mention of @shopify/web-worker; switches to vanilla postMessage for communication with the diff webworker.
> Switch from @shopify/web-worker to postMessage for useCompareExtension

- backend/coreapp/compilers.py
Just adds a couple defines we use, and `proc gekko`.
> Update `Super Smash Bros. Melee` preset

- frontend/src/components/compiler/CompilerOpts.tsx
Fixes #768.
Turns out both flags were being set at once, and given that Quantum Diffing (™️) still isn't stable, this PR fixes that.
> Fix switching diff algorithms

- frontend/src/app/(navfooter)/new/NewScratchForm.tsx
- frontend/src/app/(navfooter)/new/new.module.scss
> remove unnecessary <hr> on new scratch page

- backend/coreapp/compiler_wrapper.py
- backend/coreapp/diff_wrapper.py
- backend/coreapp/tests.py
- backend/coreapp/views/scratch.py
> Better asm diff error handling

- backend/compilers/download.py
- backend/coreapp/compilers.py
- backend/coreapp/platforms.py
- frontend/Dockerfile
Reverts decompme/decomp.me#789
> Revert "Add gcc-mipsel for PS1"

- frontend/src/components/Diff/Diff.module.scss
> Light diff colours

- frontend/src/components/Footer.tsx
> footer fix

- backend/compilers/download.py
there have been a few fixes :)
> Update maspsx in download.py

- backend/compilers/download.py
> Update maspsx hash

- backend/compilers/download.py
when I say "update", you say "maspsx"...
> Update maspsx to latest

- backend/coreapp/compilers.py
As changed by https://github.com/happyhavoc/th06/commit/b10724718c5217f13944c8d626f5becfb1f4c27d
> Enable C++ exception for Touhou 06 preset

- backend/compilers/download.py
- backend/coreapp/migrations/0036_fix_compiler_gah.py
Fixing some bugs in the last PR
> Compiler refactor (2)

- backend/coreapp/compilers.py
Based upon hearthgold. Still unsure about the exact flag, but for now those has been able to match some functions (the only different with hearthgold is the optimise for size instead of speed).
> Add PMD: Explorers of Sky preset

- backend/coreapp/compilers.py
Removed 'flags' option from compiler options
> Wind Waker Compiler Error Fix

- backend/coreapp/compilers.py
For the N64 game Bomberman Hero.
> Add Bomberman Hero preset.

- backend/coreapp/compilers.py
- backend/coreapp/libraries.py
- backend/coreapp/models/scratch.py
- backend/coreapp/serializers.py
- backend/coreapp/views/scratch.py
- frontend/src/app/(navfooter)/new/NewScratchForm.tsx
- frontend/src/components/compiler/CompilerOpts.tsx
- frontend/src/lib/api/types.ts
Just realized this could be useful 😅 .
> Add libraries support to presets

- backend/coreapp/compilers.py
> Use wibo for n64 compilers

- backend/Dockerfile
- backend/coreapp/compilers.py
- docker-compose.yaml
> Use wibo for gc wii

- .github/workflows/ci.yml
- backend/Dockerfile
- backend/coreapp/compilers.py
- docker-compose.yaml
> Use wibo for N3DS

- backend/coreapp/models/github.py
- backend/coreapp/tests.py
- backend/coreapp/views/scratch.py
- backend/decompme/settings.py
Created this as a result of looking through some of the most common sentry issues that were reported
Things (hopefully) fixed:
* Github login failures weren't being caught and handled
* Scratches with libraries couldn't be forked because of issues with the library field going from the Scratch data into a serializer and then back into a Scratch. I handled this with a hack-ish fix, but I think it's not too bad
There's still more to look into, primarily the stuff with getting user info from GitHub. So we can either handle that here or in a new PR.
> Sentry issue fixes

- .github/workflows/ci.yml
- backend/Dockerfile
- backend/coreapp/compilers.py
- docker-compose.yaml
I think we could have done this a while ago, but better late than never!
> Use wibo for NDS

- .github/ISSUE_TEMPLATE/create-update-compiler-preset.md
> Add issue template for adding compiler preset

- backend/coreapp/compilers.py
Let's see if this passes CI... (see [here](https://github.com/dosemu2/dosemu2/issues/2136) for more info).
> Provide full path to dosemu executable

- frontend/src/lib/api.ts
With thanks to @nanaian!
Closes #934.
> Don't make api call when preset is undefined

- backend/coreapp/models/github.py
- backend/coreapp/serializers.py
> Attempt to fix 500 on missing github user

- backend/poetry.lock
Update asm-differ to fix PowerPC immediate highlighting
> Fix PowerPC immediate highlighting

- backend/coreapp/admin.py
- backend/coreapp/models/scratch.py
Helps one of the tasks on #957.
> Fix editing of scratches on /admin endpoint

- .github/workflows/ci.yml
- backend/Dockerfile
- docker-compose.yaml
> Fix dosemu2

- .github/ISSUE_TEMPLATE/create-or-update-a-compiler-preset.md
- backend/coreapp/diff_wrapper.py
- backend/coreapp/views/compiler.py
- backend/coreapp/views/platform.py
> Fix the last-updated tag of some endpoints & remove win32 hack

- backend/coreapp/decompiler_wrapper.py
- backend/coreapp/tests/test_decompilation.py
- backend/coreapp/views/scratch.py
> Attempt to decompile without context if the first decompilation fails

- backend/coreapp/serializers.py
- backend/coreapp/tests/test_user.py
> Remove is_you from /api/user

- frontend/src/components/Shortcut.tsx
I invoked the Aletian Principle, and the problem is gone
> Fix getUserAgent() called on server error

- backend/coreapp/platforms.py
- frontend/src/components/Scratch/ScratchToolbar.tsx
- frontend/src/lib/api.ts
- frontend/src/lib/api/types.ts
Closes #492.
I think I've got them all?
- N64
- IRIX
- PS1
- PSP
- PS2
- GC_WII
> Add 'has_decompiler' to Platform

- backend/coreapp/flags.py
Silly bug, easy fix.
Closes #1140.
> Fix mwcc_language translation bug

- frontend/src/components/Scratch/ScratchToolbar.tsx
> Remove .. from Export and Decompile in Scratch toolbar

- frontend/src/components/PlatformSelect/PlatformName.tsx
no need to call /compilers when we only need 1 platform.
> Use /platform endpoint to fetch platform name

- backend/coreapp/platforms.py
Added dlabel to the following platforms:
- PS1
- PS2
- PSP
> Add dlabel macro to more platforms

- frontend/src/app/(navfooter)/new/NewScratchForm.tsx
- frontend/src/app/(navfooter)/settings/TextField.tsx
- frontend/src/components/SearchBox.tsx
- frontend/src/components/VerticalMenu.tsx
- frontend/src/components/compiler/CompilerOpts.tsx
Closes #1168. I dont have any spellchecking on the live site (using Chrome), so can someone confirm this change does what it should?
> Add 'spellCheck={false}' to all relevant <input> components

- backend/coreapp/asm_preludes/gba.s
- backend/coreapp/asm_preludes/gc_wii.s
- backend/coreapp/asm_preludes/irix.s
- backend/coreapp/asm_preludes/macosx.s
- backend/coreapp/asm_preludes/msdos.s
- backend/coreapp/asm_preludes/n64.s
- backend/coreapp/asm_preludes/nds_arm9.s
- backend/coreapp/asm_preludes/ps1.s
- backend/coreapp/asm_preludes/ps2.s
- backend/coreapp/asm_preludes/psp.s
- backend/coreapp/asm_preludes/saturn.s
- backend/coreapp/platforms.py
Closes #1176.
Should the `asm_preludes` directory perhaps be one level higher? or in a `platforms` directory or?
> Separate asm_prelude out of platforms.py

- backend/coreapp/tests/test_scratch.py
> Add 1 ps2 test

- frontend/src/components/Nav/Nav.tsx
Before:
[Screencast from 2024-04-23 16-31-49.webm](https://github.com/decompme/decomp.me/assets/151766738/a5b1481f-2cc9-42ce-85cc-8926ac4336bd)
After:
[Screencast from 2024-04-23 16-32-37.webm](https://github.com/decompme/decomp.me/assets/151766738/03c0b5e2-91e5-49ea-af7d-65443a703879)
> Added toggle state to hamburger menu links

- frontend/src/components/Nav/Nav.module.scss
For issue [#1173](https://github.com/decompme/decomp.me/issues/1173)
Before
[before.webm](https://github.com/decompme/decomp.me/assets/151766738/f469254e-7341-4243-8a99-be1ff005c0bf)
After
[after.webm](https://github.com/decompme/decomp.me/assets/151766738/d35a9260-6289-4d5c-9468-a506af7444ea)
> Change nav container z index

- frontend/src/components/Scratch/FamilyPanel.tsx
Fixes #737.
Tested on https://decomp.me/scratch/zzL0W.
> Fix scrolling of family panel

- frontend/src/components/compiler/CompilerOpts.tsx
> Added conditional to libraries in CompilerOpts

- frontend/src/app/(navfooter)/credits/ContributorsList.tsx
For issue [#762](https://github.com/decompme/decomp.me/issues/762)
closes https://github.com/decompme/decomp.me/issues/762
> Removed sizing for mobile and scaled down to 1/3 for contributors

- frontend/src/components/compiler/CompilerOpts.tsx
This is for issue [#825](https://github.com/decompme/decomp.me/issues/825)
[Screencast from 2024-05-01 14-48-36.webm](https://github.com/decompme/decomp.me/assets/151766738/b33e74af-3cf1-4756-a117-dcb7137e4e38)
> Added a default option to compiler options for simplification

- frontend/src/components/Editor/CodeMirror.module.scss
Fixes #678 
The rest should've been fixed in #797
> Added label coloring to fix light theme search labels

- frontend/src/app/(navfooter)/new/layout.tsx
> Restrained max width on new scratch

- backend/coreapp/views/scratch.py
- backend/coreapp/views/user.py
- frontend/src/app/(navfooter)/u/[username]/page.tsx
- frontend/src/components/Scratch/SortableFamilyList.tsx
- frontend/src/components/Sort.tsx
fixes #1234 
[Screencast from 2024-05-13 14-04-48.webm](https://github.com/decompme/decomp.me/assets/151766738/ca865c6a-a82d-4bc7-81e5-33a243dfe662)
> Fixed user page sorting

- frontend/src/components/Sort.tsx
"Most match" -> "Most matched"
> Fixed sort by typo

- backend/coreapp/views/preset.py
> Hide owner from preset search

- backend/coreapp/asm_preludes/ps2.s
Updates existing macros and adds more macros to support declaring visibility for symbols
> Update PS2 asm prelude

- backend/coreapp/flags.py
- frontend/src/lib/i18n/locales/en/compilers.json
Adds a checkbox to disable [buffer security checks](https://learn.microsoft.com/en-us/cpp/build/reference/gs-buffer-security-check?view=msvc-170) in MSVC.
> Add /GS- checkbox for MSVC

- backend/coreapp/views/user.py
Resolves #1299 
I matched this to the way query params are handled on the ScratchViewSet class. Tested locally on mock data and works as expected!
> Add filtering on preset query param to user scratch list

- backend/compilers/compilers.linux.yaml
- backend/coreapp/compilers.py
- backend/coreapp/migrations/0057_rename_ps1_mipsel_compilers.py
- frontend/src/lib/i18n/locales/en/compilers.json
> Migrate ps1 -mipsel compilers to -psx

- backend/coreapp/views/scratch.py
- frontend/src/components/Sort.tsx
This works by adding a dummy field to the queryset which we can then sort on.
Should close #1249.
> Trying to sort scratch list by match percent

- backend/poetry.lock
https://github.com/simonlindholm/asm-differ/pull/165
> Bump asm-differ

- frontend/src/components/Scratch/ScratchToolbar.tsx
> Disable 'Fork' button whilst forking

- frontend/src/components/Diff/Diff.module.scss
> Make symbols readable for non-dark theme.

- backend/coreapp/m2c_wrapper.py
Solves https://github.com/matt-kempster/m2c/issues/285.
> Pass 'mipsel' as arch to m2c for le mips arches

- .github/workflows/ci.yml
- backend/coreapp/compilers.py
- backend/coreapp/sandbox.py
- docs/DOCKER.md
Closes #1401 (for this compiler)
> Allow quotes for n64 egcs

- frontend/src/components/Nav/Search.tsx
- frontend/src/components/ScratchList.tsx
> Add match percent to search list

- backend/coreapp/compiler_wrapper.py
> Do not emit #line directive for Ido w/ Pascal

- .github/workflows/ci.yml
- backend/Dockerfile
Let's see if the tests all pass...
> Bump wibo to 0.6.16

- frontend/src/app/(navfooter)/login/page.tsx
- frontend/src/lib/oauth.ts
> Fix redirect on login

- frontend/src/components/Tabs.tsx
> Make TabCloseButton a div not a button so it can be nested in a button

- frontend/src/components/Scratch/SortableFamilyList.tsx
- frontend/src/lib/api.ts
creating a PR so i can try this out in vercel.. seemed to do as expected locally.
> Try using SWRImmutable for compilers, platforms, presets etc

- backend/coreapp/views/scratch.py
> Ensure parents are considered family 👪

- backend/coreapp/middleware.py
- backend/coreapp/views/user.py
Suggestion from [stack overflow](https://stackoverflow.com/questions/77738763/unsaved-model-instances-to-related-filters-in-tests-for-django-5-0).
> Try to fix error when yandex bot hits api/user/scratches

- frontend/src/app/(navfooter)/new/NewScratchForm.tsx
- frontend/src/app/(navfooter)/page.tsx
- frontend/src/app/(navfooter)/platform/[id]/page.tsx
- frontend/src/app/(navfooter)/preset/[id]/page.tsx
- frontend/src/components/Nav/Search.tsx
- frontend/src/components/ScratchItem.module.scss
- frontend/src/components/ScratchItem.tsx
- frontend/src/components/ScratchList.module.scss
- frontend/src/components/ScratchList.tsx
- frontend/src/components/user/tabs/ScratchesTab.tsx
This was going to be my first step to making the /preset page mobile-friendly (and converting it and scratch list to tailwind), but I ran out of steam pretty much immediately... so just committing this change.
> Split ScratchItem* from ScratchList

- backend/compilers/compilers.linux.yaml
- backend/coreapp/compilers.py
- frontend/src/lib/i18n/locales/en/compilers.json
Depends on https://github.com/decompme/compilers/pull/30
> Add more NGC ProDG compilers

- backend/compilers/compilers.linux.yaml
- backend/coreapp/compilers.py
- frontend/src/lib/i18n/locales/en/compilers.json
https://github.com/decompme/compilers/pull/31
> Add MSVC 8.0 (Patched) compiler

- backend/coreapp/middleware.py
- frontend/package.json
- frontend/src/app/(navfooter)/settings/NavItem.tsx
- frontend/src/app/(navfooter)/settings/SliderField.tsx
- frontend/src/app/(navfooter)/settings/TextField.tsx
- frontend/src/components/AsyncButton.tsx
- frontend/src/components/Breadcrumbs.tsx
- frontend/src/components/Button.tsx
- frontend/src/components/Diff/DiffRowAsmDiffer.tsx
- frontend/src/components/Diff/DiffRowObjdiff.tsx
- frontend/src/components/DismissableBanner.tsx
- frontend/src/components/Editor/CodeMirror.tsx
- frontend/src/components/GhostButton.tsx
- frontend/src/components/Nav/LoginState.tsx
- frontend/src/components/Nav/Nav.tsx
- frontend/src/components/Nav/Search.tsx
- frontend/src/components/NumberInput.tsx
- frontend/src/components/PlatformSelect/PlatformSelect.tsx
- frontend/src/components/PlatformSelect/ScrollingPlatformIcons.tsx
- frontend/src/components/PresetList.tsx
- frontend/src/components/ScoreBadge.tsx
- frontend/src/components/Scratch/ScratchToolbar.tsx
- frontend/src/components/Scratch/SortableFamilyList.tsx
- frontend/src/components/ScratchItem.tsx
- frontend/src/components/ScratchList.tsx
- frontend/src/components/Tabs.tsx
- frontend/src/components/VerticalMenu.tsx
- frontend/src/components/user/AnonymousFrog.tsx
- frontend/src/components/user/UserAvatar.tsx
- frontend/yarn.lock
Solves https://github.com/decompme/decomp.me/issues/1259
> Replace `classnames` with `clsx`

- frontend/src/app/(navfooter)/settings/appearance/AppearanceSettings.tsx
This library is unmaintained, but this bug is annoying me, so here's a workaround
> Workaround use-persisted-state bug

- frontend/package.json
- frontend/src/app/(navfooter)/settings/appearance/AppearanceSettings.tsx
- frontend/src/lib/settings.ts
- frontend/src/lib/storage.ts
- frontend/src/misc_types.d.ts
- frontend/yarn.lock
Follow up to #1499. For some reason, I decided to write a React hook to replace `use-persisted-state`. I think it's pretty neat. I'll definitely be copying it into my own projects.
https://github.com/user-attachments/assets/cd33fb9a-2f75-4d18-8dd3-731386f279bf
> Replace unmaintained `use-persisted-state`

- backend/coreapp/flags.py
- frontend/src/lib/i18n/locales/en/compilers.json
> Add -O0,p and -O0,s flags to MWCC

- backend/coreapp/urls.py
- backend/coreapp/views/search.py
- frontend/src/components/Nav/Search.tsx
- frontend/src/lib/api/types.ts
Relatively straightforward, can expand to search more things if we wanted to...
e.g.
> Search bar now also searches for users and presets

- frontend/src/components/Nav/Nav.tsx
- frontend/src/components/Nav/Search.module.scss
You can check the vercel deployment but
before
after
> Allow search bar to grow a bit

- frontend/src/components/Diff/Diff.tsx
- frontend/src/components/Diff/DiffRowAsmDiffer.tsx
- frontend/src/components/Editor/CodeMirror.tsx
- frontend/src/components/Scratch/hooks/useLanguageServer.ts
> MutableRefObject is deprecated, replace with RefObject

- backend/compilers/compilers.linux.yaml
- backend/coreapp/compilers.py
- frontend/src/lib/i18n/locales/en/compilers.json
Relies on https://github.com/decompme/compilers/pull/36
> Add gc_wii mwcc_233_159p1 (GC/1.1p1)

- frontend/src/components/Diff/ObjdiffPanel.tsx
- frontend/src/components/Scratch/Scratch.tsx
> Pass more data to objdiff

- backend/Dockerfile
- backend/Dockerfile.prod
- backend/libraries/download.py
> Remove 'git' requirement from library downloader

- backend/coreapp/decompiler_wrapper.py
- backend/coreapp/m2c_wrapper.py
- backend/poetry.lock
... and also use "mipsee" rather than "mipsel" where relevant while we're at it, to get the ABI right.
> m2c for ARM

- backend/coreapp/asm_preludes/irix.s
- backend/coreapp/asm_preludes/n64.s
- backend/coreapp/asm_preludes/ps1.s
- backend/coreapp/asm_preludes/ps2.s
- backend/coreapp/asm_preludes/psp.s
Update the label macro definitions, following the changes introduced in the splat PR https://github.com/ethteck/splat/pull/466 
I'm not sure if I need to update any other file besides the `.inc` files.
> Update labels used by splat

- backend/coreapp/compilers.py
- frontend/src/lib/i18n/locales/en/compilers.json
Made this change in github UI, haven't tested it. Is there a quick way to test if the backend works?
> add "experimental" SN 2.8.1 C++ compiler (in order to preserve line numbers)

- frontend/src/components/Diff/DiffRowAsmDiffer.tsx
> Fix diff cell background color setting

- frontend/next.config.js
- frontend/package.json
- frontend/src/app/(navfooter)/privacy/page.tsx
- frontend/src/app/layout.tsx
- frontend/src/components/Footer.tsx
- frontend/yarn.lock
1. Not very interesting with all traffic going through Cloudflare
2. Even less interesting with Under Attack mode enabled
> Remove plausible
